### ISSUE TITLE
test suites fail on Windows when compiled with Mingw32

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1102] opened 2017-09-26 09:48 UTC
### Description
- Type: Bug 
- Priority: Major 

## Bug

**OS**  
windows using mingw32

**mbed TLS build:**  
Version:development branch
OS version: Windows 10
Configuration: default
compiled using mingw32:
`mingw32-make.exe CC=mingw32-gcc.exe LDFLAGS=-lws2_32`

**Expected behavior**   
tests suites to pass
**Actual behavior**  
tests suites fail
**Steps to reproduce**  

1. copmile the library using mingw32:
`mingw32-make.exe CC=mingw32-gcc.exe LDFLAGS=-lws2_32 `
2. run any test suite in `tests` folder ( I tests sporadically a few test suites)

**Comment by andresag01** [comment] 2017-09-26 10:56
@RonEld: Are these test suites supposed to pass? What terminal are you running them on? For example, I would expect them to fail in cmd.exe because the test suites look for files using `/` instead of `\`...

**Comment by RonEld** [comment] 2017-09-26 10:59
@andresag01 I'm not sure actually, I don't recall if we ever ran these tests on Windows.
Changed to enhancement since I think it  it would be nice to have them run on Windows as well

**Comment by andresag01** [comment] 2017-09-26 11:26
@hanno-arm, do you have any information about this?

**Comment by ciarmcom** [comment] 2017-09-26 11:51
ARM Internal Ref: IOTSSL-1777

**Comment by sbutcher-arm** [comment] 2018-06-13 12:54
Running the tests on my Windows 7 VM, with a very recent version of mingw, using the same steps as above, the tests pass. Therefore whatever the problem was, I can't reproduce it and I believe has either been fixed or was a user issue.

Specifically, I ran the following command:
```
mingw32-make.exe CC=mingw32-gcc.exe LDFLAGS=-lws2_32 test
```
On Windows 7, with gcc version 6.3.0 from mingw.

Therefore I'm closing the issue. If anyone still has a problem, please feel free to reopen the bug.

**Closed by sbutcher-arm** 2018-06-13 12:54 UTC
Labels: enhancement, mirrored, tracking
