### ISSUE TITLE
threading_mutex_init_pthread fail

### ISSUE THREAD

**Issue by yanesca** [ARMmbed/mbedtls#667] opened 2016-10-28 13:55 UTC
`hreading_mutex_init_pthread` fails whenever `mutex->is_valid` is not 0. 

It is the right behaviour if it is nonzero because it has been initialised (in the sense of calling this init function) before. 

Unfortunately `mutex->is_valid` can be nonzero too if the `mbedtls_threading_mutex_t` structure hasn't been initialised (in the sense of initialising variables in the C language).

In this latter case the current implementation the init function will return without doing anything and every operation involving these mutexes will fail.

**Comment by andresag01** [comment] 2017-05-02 12:41
I believe this is a duplicate of https://github.com/ARMmbed/mbedtls/issues/843.

**Comment by sbutcher-arm** [comment] 2017-05-15 11:00
PR merged. Issue can now be closed.

**Closed by sbutcher-arm** 2017-05-15 11:00 UTC
Labels: bug
