### ISSUE TITLE
X.509 test failure in configuration without SHA-1 and without 1/n-1 record splitting

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#911] opened 2017-05-11 15:16 UTC
On the configuration below, the test `test_suite_x509parse` fails:

```
X509 CRL Malformed Input (trailing spaces at end of file) ......... FAILED
  mbedtls_x509_crl_parse_file( &crl, crl_file ) == result
  at line 175, suites/test_suite_x509parse.function
```

Observed on tag `mbedtls-2.4.2` and in `development` as I write. Originally found by @andresag01 [while reviewing](https://github.com/ARMmbed/mbedtls/pull/904#issuecomment-300813372).

```
diff --git a/include/mbedtls/config.h b/include/mbedtls/config.h
index 0f7e29b..733412d 100644
--- a/include/mbedtls/config.h
+++ b/include/mbedtls/config.h
@@ -1043,7 +1043,7 @@
  *
  * Comment this macro to disable 1/n-1 record splitting.
  */
-#define MBEDTLS_SSL_CBC_RECORD_SPLITTING
+//#define MBEDTLS_SSL_CBC_RECORD_SPLITTING
 
 /**
  * \def MBEDTLS_SSL_RENEGOTIATION
@@ -1111,7 +1111,7 @@
  *
  * Comment this macro to disable support for TLS 1.0
  */
-#define MBEDTLS_SSL_PROTO_TLS1
+//#define MBEDTLS_SSL_PROTO_TLS1
 
 /**
  * \def MBEDTLS_SSL_PROTO_TLS1_1
@@ -1123,7 +1123,7 @@
  *
  * Comment this macro to disable support for TLS 1.1 / DTLS 1.0
  */
-#define MBEDTLS_SSL_PROTO_TLS1_1
+//#define MBEDTLS_SSL_PROTO_TLS1_1
 
 /**
  * \def MBEDTLS_SSL_PROTO_TLS1_2
@@ -2190,7 +2190,7 @@
  *
  * This module is required for SSL/TLS and SHA1-signed certificates.
  */
-#define MBEDTLS_SHA1_C
+//#define MBEDTLS_SHA1_C
 
 /**
  * \def MBEDTLS_SHA256_C
```

**Comment by mpg** [comment] 2017-05-11 15:22
I don't think record spliting has anything to do with it, other than that when you disable sha-1 you need to disable tls 1.0 and ssl 3.0 and when you disable those you need to disable record splitting.

**Comment by gilles-peskine-arm** [comment] 2017-05-11 15:35
@mpg Ok, thanks for looking, then I guess the bug is in `check_config.h` and the documentation which don't rule out this configuration

**Comment by andresag01** [comment] 2017-05-11 15:54
Ok, so I did a quick test and figured out the problem. The problem is that the test is reading the datafile `data_files/crl-malformed-trailing-spaces.pem` which uses `ecdsa-with-SHA1`. The test is missing preprocessor conditions in the `depends_on` part as it only has `MBEDTLS_PEM_PARSE_C`

**Comment by mpg** [comment] 2017-05-11 16:00
Ah, checked at the same time and came to the same conclusion.

**Comment by ciarmcom** [comment] 2017-05-23 11:50
ARM Internal Ref: IOTSSL-1403

**Comment by RonEld** [comment] 2018-07-24 11:38
Closing, as I believe this issue was fixed and merged.

**Closed by RonEld** 2018-07-24 11:38 UTC
Labels: bug, fix available, mirrored, tracking
