### ISSUE TITLE
Freeing of already freed pointer possible

### ISSUE THREAD

**Issue by ptahpeteh** [ARMmbed/mbedtls#367] opened 2015-12-08 15:36 UTC
In file **asn1write.c**, function *mbedtls_asn1_store_named_data()*, lines 311 and on:
```c
    if( ( cur = mbedtls_asn1_find_named_data( *head, oid, oid_len ) ) == NULL )
    {
        // .....
    }
    else if( cur->val.len < val_len )
    {
        // Enlarge existing value buffer if needed
        //
        mbedtls_free( cur->val.p );
        cur->val.p = NULL;

        cur->val.len = val_len;
        cur->val.p = mbedtls_calloc( 1, val_len );
        if( cur->val.p == NULL )
        {
            mbedtls_free( cur->oid.p );
            // frees a linked list element but doesn't update previous elem's next pointer
            mbedtls_free( cur );                  
            return( NULL );
        }
    }
```
This looks like a bug to me that can lead to freeing already freed pointer. *mbedtls_asn1_find_named_data()* returns a pointer to an element to be updated, then this pointer can be freed but it's not removed from the linked list. So it still can be accessed through the list, overwritten or freed later on.

**Comment by ciarmcom** [comment] 2015-12-08 17:05
ARM Internal Ref: IOTSSL-566

**Comment by mpg** [comment] 2015-12-10 10:13
Thanks for your report! This will be fixed.

Also, let me remind your that bugs that could have security implications (such as this one, even if in that case the impact happens to be low) should be reported by email to whitehat@polarssl.org in order to allow use to better coordinate the release of the fix in case the issue is more severe.

**Closed** 2015-12-23 16:43 UTC
Labels: mirrored
