### ISSUE TITLE
adjust include paths

### ISSUE THREAD

**Issue by GregSlazinski** [ARMmbed/mbedtls#1225] opened 2017-12-20 23:16 UTC
replace
https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L55
https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/platform.h#L33
#include "mbedtls/platform_time.h"
with
#include "platform_time.h"

these files are in the same folder, so the paths should not include "mbedtls/"

I'm trying to include the headers in a standalone project and I'm getting errors about"mbedtls/*" file not found.
After doing the replacements, the headers compile OK.

**Comment by RonEld** [comment] 2017-12-21 08:09
Hi @GregSlazinski Thank you for raising this issue!
I believe that this is a duplicate of #857 , and that #921 fixes this issue

**Closed** 2017-12-24 19:56 UTC
Labels: bug, fix available
