### ISSUE TITLE
mbedtls accepts a certificate which has extensions but no authority key identifier

### ISSUE THREAD

**Issue by chenchuAtXidian** [ARMmbed/mbedtls#802] opened 2017-02-13 14:35 UTC
Summary: As for a certificate which has extensions, it should have authority key identifier according to RFCs 5280 and 6818.
   
   Versions of mbedTLS: 2.3.0
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  mbedtls_cert_app mode='file' filename=16.pem ca_file=ca.pem
   
   Actual results: OK
   Expected results: mbedTLS should reject such a certificate.
   
   The attachement contains ca.pem and 16.pem.
   
   Please rename the file "test cases.txt" to "test cases.zip" and extract it.

[test cases.txt](https://github.com/ARMmbed/mbedtls/files/771338/test.cases.txt)

**Comment by ciarmcom** [comment] 2017-02-13 20:50
ARM Internal Ref: IOTSSL-1216

**Comment by NWilson** [comment] 2017-02-15 22:04
Surely this can't be a bug? AuthorityKeyIdentifier is desirable, but there is absolutely no reason to reject a certificate lacking it.

Indeed, the wider issue is that AuthorityKeyIdentifier is not implemented at all by mbedTLS - I have submitted Pull Requests for it at least once. I am and currently awaiting feedback on several PRs over a year old, and one of the branches which is waiting for review includes AKI/SKI support.

Finally, you mention RFCs 5280 and 6818, however RFC6818 does not seem to mention AKI/SKI at all; and RFC 5218 places only a weak requirement on clients, and certainly does not advocate rejecting certificates without an AuthorityKeyIdentifier: "This profile RECOMMENDS support for the key identifier method by all certificate users."

**Comment by mpg** [comment] 2018-03-19 12:16
@chenchuAtXidian Thanks for your report and your interest in Mbed TLS, and sorry for the long delay in our response.

We checked RFC 5280 and we don't think it requires validating parties to enforce the presence of this extension. Quite the opposite, it explicitly allows issuing CAs to omit it under some circumstances:
```
                                                                  There is one exception;
   where a CA distributes its public key in the form of a "self-signed"
   certificate, the authority key identifier MAY be omitted.
```
which implies that it would be wrong for validating parties to always enforce its presence. We didn't find any part of the RFC that requires validating parties to enforce the presence of this extension even in limited circumstances.

Therefore we are closing this issue as "not a bug".

If you disagree with this evaluation, please re-open this issue and quote the exact bits of the RFC (or other applicable standards document) that require validating parties to enforce the presence of this extension.

@NWilson we are aware of, and sorry about, our currently very long delay in evaluating community PRs for merging. We are working on it and hope to improve the situation in the near future. Thanks for your continued interest in Mbed TLS.

**Closed** 2018-03-19 12:16 UTC
Labels: bug, mirrored, tracking
