### ISSUE TITLE
Question on branches / Releases..

### ISSUE THREAD

**Issue by MarcKarasek** [ARMmbed/mbedtls#3349] opened 2020-05-22 20:42 UTC
#1950  Question

What is the difference between 
2.16.x and the 2.7.x Releases

Also what is the branch baremetal?  Is this equivalent to either of the above?

**Comment by hanno-arm** [comment] 2020-05-22 21:01
Hi @MarcKarasek,

Mbed TLS 2.16.x and 2.7.x are support branches. They receive release containing bugfixes are backported, but not new features.

Baremetal is a special branch which contains a large number of code-size and RAM optimizations. Those optimizations are mostly applicable to upstream Mbed TLS as well, and some but by far not all of them have been ported. Someone from the team might comment on if there are plans on doing so. If this is of interest to you, let me know and I can give some more pointers on how to use the baremetal branch.

Regards,
Hanno

**Comment by MarcKarasek** [comment] 2020-05-22 21:17
What is the difference between 2.7 and 2.16?   Is one more current than the other?  
I am interested in the baremetal but have gotten the development (need to move over to a release branch) to compile for our bare metal as well as our Linux both based on RISCV.  Still need to do some testing/integration but at least it compiles into a library. :-)

**Comment by gilles-peskine-arm** [comment] 2020-05-22 21:40
The number after the dot increases with each version, so 2.16 is more recent than 2.7. We currently maintain three versions: [mbedtls-2.7](https://github.com/ARMmbed/mbedtls/tree/mbedtls-2.7) (bug fixes only), [2.16](https://github.com/ARMmbed/mbedtls/tree/mbedtls-2.16) (bug fixes only), [development](https://github.com/ARMmbed/mbedtls/tree/development) (default branch, currently at 2.22, that's where new features go).

The [baremetal](https://github.com/ARMmbed/mbedtls/tree/baremetal) branch is an experimental branch which is based on 2.16, with extra work to reduce the code size and the RAM usage further, but sacrificing some features and stability. We intend to merge baremetal and development in the long term, but it won't be soon.

You should only use the baremetal branch if you have extremely tight requirements — typically on platforms where 128kB of RAM or code size is considered a large number. If your platform is big enough to run Linux, don't use baremetal. The normal version of the library can be compiled for bare metal environments.

**Comment by gilles-peskine-arm** [comment] 2020-05-22 21:41
I'm closing this issue because it is not a bug report or a feature request. In the future, please post support questions to the [mailiing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls).

**Closed by gilles-peskine-arm** 2020-05-22 21:41 UTC
