### ISSUE TITLE
x509_crt_verify_child() shouldn't directly look for a grandparent in trusted CA

### ISSUE THREAD

**Issue by luocm** [ARMmbed/mbedtls#826] opened 2017-03-01 10:19 UTC
The following piece of code will result in missing check the top cert in the cert chain, if the top cert itselft is somewhat a fake CA file (e.g., same issuer name and subject name as the valid CA)
 
   /* Look for a grandparent in trusted CAs */
    for( grandparent = trust_ca;
         grandparent != NULL;
         grandparent = grandparent->next )
    {
        if( x509_crt_check_parent( parent, grandparent,
                                   0, path_cnt == 0 ) == 0 )
            break;
    }

    if( grandparent != NULL )
    {
        ret = x509_crt_verify_top( parent, grandparent, ca_crl, profile,
                                path_cnt + 1, self_cnt, &parent_flags, f_vrfy, p_vrfy );
        if( ret != 0 )
            return( ret );
    }

**Comment by ciarmcom** [comment] 2017-08-29 15:51
ARM Internal Ref: IOTSSL-1677

**Comment by NWilson** [comment] 2017-08-30 20:56
This is potentially similar to an issue I've remarked on before? I have/had a PR for refactoring the chain-building code, but it's been open for so long I've forgotten the details! (I admit I haven't done much to help push it forwards.) The way the parent/grandparent certs are searched for doesn't always build the same chains as other TLS libraries. And, the code is also very long, which could contribute to these problems, with about two or three times as much code+branches as necessary, since the parent/grandparent checks are duplicated in several different locations (_child/_top) rather than checking each link of the chain once in one shared function.

**Comment by mpg** [comment] 2017-08-31 08:05
@luocm Thanks for your report!

If I understand correctly, you're thinking about a situation where the peer sends us a chain like A, B, C' where C' is a fake version of C, a CA that we trust? In that case one of two things can happen: either B is correctly signed by C, and our code will accept the chain, or it isn't, and our code will flag it a unstrusted as there is no path leading to a trusted root with good signatures all along.

Please tell me if I misunderstood your point or if you disagree with my analysis.

@NWilson I'm happy to say that we recently worked on refactoring that part of the code. If you're interested, you can have a look at [that branch](https://github.com/mpg/mbedtls/tree/iotssl-1381-x509-verify-refactor), which should be merged soon. It's sort of an expanded version of yours, where we started by adding more tests, and worked in a more incremental way, with emphasis placed on preserving existing behaviour (which, in some cases, might be changed later - but we wanted to clearly separate that from the refactoring).

**Comment by luocm** [comment] 2017-08-31 08:18
@mpg I should say C' is another CA comes from the same signer X as C. Eventually B is signed by X use C', but what I trust is C.

**Comment by mpg** [comment] 2017-08-31 08:26
Thanks for that precision, though I'm afraid I still don't get why this is a problem in practice. Can you please state:
- the situation you're considering (list of certs provided, list of trusted roots)
- what behaviour you expect in this situation
- what behaviour you observe instead
- why the behaviour you observe is less satisfying to you as the behaviour you expected?
Thanks!

**Comment by luocm** [comment] 2017-08-31 08:53
@mpg , e.g.
CA org X has two CA files: C1 and C2
X has signed child B use C2,  the ower of B signed child A
I trust C1
The peer send me A, B and C2, because B is not signed by C1, so when I use C1 to verify the peer, I assume it should tell failure, but actually it passed the verification.

**Comment by luocm** [comment] 2017-08-31 09:06
@mpg , this case only happens, actually, when the CA org X create two CA files( C1 and C2) using the same private key and public key.

**Comment by mpg** [comment] 2017-08-31 10:04
Well if C1 and C2 share the same key and have the same Subject Name, then it seems to me that any certificate that is signed by C2 is also signed by C1 and vice-versa. What makes you think C1 is not a valid parent for B?

**Comment by luocm** [comment] 2017-08-31 10:09
What I found is C1 and C2 share the same key, but have  different Subject Name (maybe for  different usage)

**Comment by mpg** [comment] 2017-08-31 10:15
Ok, so if they have different Subject Name, then only one of those two names is the Issuer Name of B. Which one is it? If it's C1, then we're right to accept it and it seems wrong for the peer to send C2 as part of the chain. If it's C2, then we're wrong to accept this chain as trusted, but to be honest that would surprise me.

By any chance, would you be able to share those certificates publicly so that I can try reproducing your situation?

**Comment by luocm** [comment] 2017-08-31 10:22
As mentioned above, C1's Subject Name is  is the Issuer Name of B. What the peer sent is A, B and C1.
But what I trusted is C2.
Er, I shouldn't disclose the certs.

**Comment by mpg** [comment] 2017-08-31 10:28
Ok, I'm afraid we switched names at some point, because if your message from 2h ago I read "I trust C1" and in your latest "what I trusted is C2."

No problem that you can't disclose the certs, of course. I'll try to create example certs to reproduce the situation.

**Comment by luocm** [comment] 2017-08-31 10:32
Sorry for the typo. for the example mentioned 2h ago, it should be:
C2's Subject Name is is the Issuer Name of B. What the peer sent is A, B and C2.
But what I trusted is C1.

**Closed** 2019-06-13 11:08 UTC
Labels: archived, bug, component: X.509, mirrored, open for community contribution
