### ISSUE TITLE
MBEDTLS_PLATFORM_{CALLOC,FREE}_MACRO do not work as expected

### ISSUE THREAD

**Issue by ole-de** [ARMmbed/mbedtls#882] opened 2017-04-24 17:38 UTC
I would like to define the MBEDTLS_PLATFORM_CALLOC_MACRO and the MBEDTLS_PLATFORM_FREE_MACRO, i.e. provide my own implementations of calloc() and free(). The checks in check_config.h require to have MBEDTLS_PLATFORM_C and MBEDTLS_PLATFORM_MEMORY also defined in this case. When I do so, I get the following errors during compile:

platform.c:53: error: 'my_calloc' redeclared as different kind of symbol
platform.c:54: error: 'my_free' redeclared as different kind of symbol

I think, this is an issue in platform.c, line 33-62. This code should not be
compiled, if MBEDTLS_PLATFORM_{CALLOC,FREE}_MACRO are defined.

**Comment by sbutcher-arm** [comment] 2017-04-26 21:50
Yes, I think you're right. We seem to have made a mistake in the macros in this area. Thanks for highlighting it. We'll take a look.

**Comment by ciarmcom** [comment] 2017-04-26 23:51
ARM Internal Ref: IOTSSL-1363

**Comment by hanno-arm** [comment] 2018-10-23 12:56
Duplicate of #1642 and #1706, fixed through #2079. 

@sbutcher-arm Please review this assessment and close if you agree.

**Comment by RonEld** [comment] 2018-10-23 13:12
@hanno-arm I agree that this is addresses the same issue, but #1706 and #1642 are actually duplicates of this issue, as this issue preceded

**Comment by hanno-arm** [comment] 2018-10-23 13:44
@RonEld I don't mind too much what we close, as long we keep only one issue open.

**Closed** 2018-11-08 13:53 UTC
Labels: bug, fix available, mirrored, tracking
