### ISSUE TITLE
unknown type name 'mbedtls_ecp_restart_ctx'

### ISSUE THREAD

**Issue by jwhui** [ARMmbed/mbedtls#2242] opened 2018-11-28 21:31 UTC
### Description
- Type: Bug
- Priority: Minor

**mbed TLS build:**  
Version: 2.14.0
Configuration: `MBEDTLS_ECP_ALT` defined and `MBEDTLS_ECP_RESTARTABLE` not defined

**Expected behavior**   
Compiles without error.

**Actual behavior**  
`error: unknown type name 'mbedtls_ecp_restart_ctx'`

**Steps to reproduce**  
1. Define `MBEDTLS_ECP_ALT` and do not define `MBEDTLS_ECP_RESTARTABLE` in config.
2. Compile `library/ecdh.c`.

I could simply add `typedef void mbedtls_ecp_restart_ctx;` to my config to fix the above issue, but is that expected?

**Comment by RonEld** [comment] 2018-12-02 06:50
As you can see from my previous comment, `mbedtls_ecp_restart_ctx ` should be defined even if `MBEDTLS_ECP_RESTARTABLE` is not defined, as it is used in other API, such as ecdh and ecdsa. `ecp_alt.h` is used to define your alternative implementation structures. Since it is not predictable how every platform will need to define their contexts.
Having said that, I agree that in matters of `mbedtls_ecp_restart_ctx`, when `MBEDTLS_ECP_RESTARTABLE` is not defined, it is perhaps not the best design, and we may consider moving the definition referenced earlier, to a location independent on `MBEDTLS_ECP_ALT`.

**Comment by mpg** [comment] 2018-12-20 08:54
Hi @jwhui and thanks for your report! Sorry for replying so late. After analyzing the issue, I fully agree with my colleague @RonEld:

- currently you have to add something like `typedef void mbedtls_ecp_restart_ctx;` somewhere and the ideal place is your `ecp_alt.h`
- however, we acknowledge that's a bit of an annoyance, and I can confirm that's one we didn't fully anticipate when designing restartable ECC
- so I think we'll consider removing the requirement for you to define that type in your `ecp_alt.h`, probably by moving its definition out of the the `MBEDTLS_ECP_ALT` guards as @RonEld suggests, as it looks like the simplest way to solve the issue.

**Comment by mpg** [comment] 2018-12-20 08:58
I'm relabeling as a bug, as I think that's a regression: existing `ecp_alt` code that was working and correct with Mbed TLS 2.13.0 will no longer build with Mbed TLS 2.14.0 (until it's modified to add the type definition). This is a break of our compatibility promises, it should not have happened, and should be fixed.

**Comment by RonEld** [comment] 2018-12-20 11:12
@mpg I am not entirely convinced this is a bug.
One can have an alternative implementation for the restartable feature as well, in which case, `mbedtls_ecp_restart_ctx` will be defined differently.

**Comment by mpg** [comment] 2018-12-20 11:50
@RonEld I think we ruled out alternative implementations of the restartable feature: https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/check_config.h#L111 - when we did that, we should have moved the type out of the ALT guard, as it's not ALTable.

**Comment by RonEld** [comment] 2018-12-20 11:53
@mpg thank for the reminder! ( I believe I even made that change:) )

**Comment by jwhui** [comment] 2018-12-21 00:01
@mpg @RonEld, thanks for looking into this!

**Comment by sbutcher-arm** [comment] 2019-01-11 14:31
PR's #2334 and #2336 have been merged so this issue can now be closed.

**Closed by sbutcher-arm** 2019-01-11 14:31 UTC
Labels: bug, component: Crypto, fix available, mirrored, tracking
