### ISSUE TITLE
Mingw32: _vsnprintf_s does not exist on msvcrt.dll on Windows 2003

### ISSUE THREAD

**Issue by sithglan** [ARMmbed/mbedtls#355] opened 2015-11-21 12:27 UTC
Hello,
I use mbedtls on Windows 2003. I get the following error: The procedure entry point _vsnprintf_s could not be located in the dynamic link library msvcrt.dll. It is used because _TRUNCATE is defined in
/usr/i686-w64-mingw32/include/_mingw.h. As a workaround I use the attached patch, but is there a better solution?

Cheers,
      Thomas
[0001-Remove-calls-to-_vsnprintf_s-as-it-is-not-part-of-ms.txt](https://github.com/ARMmbed/mbedtls/files/40812/0001-Remove-calls-to-_vsnprintf_s-as-it-is-not-part-of-ms.txt)

**Comment by ciarmcom** [comment] 2015-11-23 11:14
ARM Internal Ref: IOTSSL-551

**Comment by sbutcher-arm** [comment] 2016-01-01 03:09
Hi @sithglan.

Although the file msvcrt.dll is pre-installed on Windows, it's actually part of Visual Studio, and I believe the name is a shortening of 'Microsoft Visual C Runtime'. You may have an older version on Windows Server 2003, but Microsoft do provide newer versions that can be installed. See here for the [Microsoft Visual C++ 2010 SP1 Redistributable Package (x64)](https://www.microsoft.com/en-gb/download/details.aspx?id=13523) which contains a newer version of msvcrt.dll, that according to MSDN [here](https://msdn.microsoft.com/en-us/library/d3xd30zz(v=vs.100).aspx) should contain a version of the runtime with the correct function. If you search around you should be able to find a combination of versions (Visual Studio 2010/2012/2015 etc) that suit your platform (Windows Server 2003) and architecture (e.g. i386 vs AMD64).

Please note, I haven't tested this out, so may have missed an issue.

Because the dependency - msvcrt.dll can be updated on platforms as old as Windows XP and Windows Server 2003, I don't think there should be a need to change mbed TLS, so I'm closing this defect. If you have any problems with changing msvrtldll, please let us know and we can revisit this. 

Hope this helps.

**Comment by sithglan** [comment] 2016-01-01 09:00
Hello sbutcher,
for me this is not an option. Because what you tell me, that in order to use a 256 KB programm, I need to download a 40 MByte runtime in order to use it. Also it requires Administrator access which I may not have. So that is not really an option. So mbedtls runs on an unpatched Windows 2003/XP with one exception: This function. So if you don't care about this platform, this is fine for me. I'll continue to use the out of tree patch I already use since I submitted the patch but I really think this is the wrong way of doing this. This is why I submitted the error and patch.

Cheers,
      Thomas

**Comment by sbutcher-arm** [comment] 2016-01-01 10:46
Hi @sithglan,

I can appreciate your position. If you look at the issues here on github and on the forum, you'll see this isn't the only problem we have related to versions of Visual Studio earlier than 2010, (which because mingw uses the msvcrt.dll runtime I'll class this as).

I'll reopen the bug for the moment, while we decide what we want to do with these older Microsoft platforms, and if we can support them. If we do, I may come back to you and ask you to sign a CLA to use your patch.

As a final point - to make use of the msvcrt.dll in the .msi I gave above - you may not need to install the .msi itself as administrator, but simply need to extract the .dll (and any dependencies) out of the .msi, and copy them locally with your application code.

**Comment by sithglan** [comment] 2016-01-01 11:04
Hello @sbutcher-arm,
thank you for considering. My patch is trivial but I'm happy to sign a CLA if necessary. To explain my usecase a little bit more. I provide one executable to my users. They download an run it. I want to keep it as easy as possible. So distributing any additional files is not an option.

Cheers,
      Thomas

**Comment by NWilson** [comment] 2016-01-01 12:06
I had a quick look into this, in case it was related to a PR I have open about Visual Studio support (PR https://github.com/ARMmbed/mbedtls/pull/353). It isn't, but now I've worked out what the problem is I hope you don't mind if I add my opinion!

On Windows, the "normal" compiler is Visual Studio, which comes with a CRT (=libc) in the form of a DLL and a static library. It's up to the application developer to choose whether to link to it dynamically or statically. If you link dynamically, the correct DLL version needs to be present on the customer's machine, either by installing the "Microsoft Visual C++ 20XX Redistributable" along with your application, or just shipping the DLL. That's why many (most?) applications link statically, which slightly increases binary sizes but the resulting exes are universal and have no CRT dependency.

What's different with MinGW is that it doesn't offer a way to statically link to the CRT (because it's "not free enough"). So instead it tries to link to the version-independent functions from the msvcrt.dll that ships with Windows, which doesn't contain _vsnprintf_s on Windows XP.

So, the options are: (1) tell mbedTLS users to use Visual Studio instead; (2) tell users you don't support Windows XP with MinGW (an odd combination of an out-of-support OS with an unusual compiler); or (3) don't call _vsnprintf_s on MinGW.

Getting rid of the calls to _vsnprintf_s will cause compiler warnings on Visual Studio, so a better patch would be to blacklist MinGW like this:

	--- a/library/platform.c
	+++ b/library/platform.c
	@@ -74,16 +74,12 @@ int mbedtls_platform_win32_snprintf( char *s, size_t n, const char *fmt, ... )
			 return( -1 );
	 
		 va_start( argp, fmt );
	-#if defined(_TRUNCATE)
	+#if defined(_TRUNCATE) && !defined(__MINGW32__)
	     ret = _vsnprintf_s( s, n, _TRUNCATE, fmt, argp );
	 #else
		 ret = _vsnprintf( s, n, fmt, argp );
		 if( ret < 0 || (size_t) ret == n )
		 {

**Comment by sithglan** [comment] 2016-01-01 13:38
Hello @NWilson,
thank you for getting to the bottom of this. I think you're fix is the way to go. I produced a small patch which fixes both occurances in the source code and tested it on Windows 2003.

Cheers,
        Thomas
[0001-Blacklist-_vsnprintf_s-on-MINGW-to-main-downward-com.txt](https://github.com/ARMmbed/mbedtls/files/75905/0001-Blacklist-_vsnprintf_s-on-MINGW-to-main-downward-com.txt)

**Comment by sbutcher-arm** [comment] 2016-06-01 18:26
Hi @sithglan,

If you'd still be happy to sign or agree to a Contributor's License Agreement (CLA), I think we should accept your patch and close this, by now, quite old defect. Unfortunately, the alternative is probably to close the issue unfixed as it's unlikely anyone else will submit another fix, and it's not something the team can spend time on.

You can [find an agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and [accept a slightly different agreement here with a click through](https://developer.mbed.org/contributor_agreement/) if this is a personal contribution. 

Apologies for the long, long delay on resolving this, which is my fault for prematurely closing the issue.

**Comment by sithglan** [comment] 2016-06-01 19:57
Hello Simon,

* Simon Butcher  [2016-06-01 20:31]:
> If you'd still be happy to sign or agree to a Contributor's License
> Agreement (CLA), I think we should accept your patch and close this,
> by now, quite old defect. Unfortunately, the alternative is probably
> to close the issue unfixed as it's unlikely anyone else will submit
> another fix, and it's not something the team can spend time on.

find the signed CLA in separate post. Find attached the two patches to
make mbedtls work. Also note that I incorporated Nicholas Wilson
suggestion.

Cheers,
        Thomas

From a076a0d8cec28ed14e6fb5c387a357fa5c6dc597 Mon Sep 17 00:00:00 2001
From: Thomas Glanzmann <thomas@glanzmann.de>
Date: Fri, 1 Jan 2016 13:29:29 +0100
Subject: [PATCH] Blacklist _vsnprintf_s on MINGW to maintain downward
 compatibility for Windows 2003/XP

---
 library/debug.c    | 2 +-
 library/platform.c | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/library/debug.c b/library/debug.c
index 4752ab1..afa21cb 100644
--- a/library/debug.c
+++ b/library/debug.c
@@ -90,7 +90,7 @@ void mbedtls_debug_print_msg( const mbedtls_ssl_context *ssl, int level,
 
     va_start( argp, format );
 #if defined(_WIN32)
-#if defined(_TRUNCATE)
+#if defined(_TRUNCATE) && !defined(__MINGW32__)
     ret = _vsnprintf_s( str, DEBUG_BUF_SIZE, _TRUNCATE, format, argp );
 #else
     ret = _vsnprintf( str, DEBUG_BUF_SIZE, format, argp );
diff --git a/library/platform.c b/library/platform.c
index d634c62..e90dc3c 100644
--- a/library/platform.c
+++ b/library/platform.c
@@ -74,7 +74,7 @@ int mbedtls_platform_win32_snprintf( char *s, size_t n, const char *fmt, ... )
         return( -1 );
 
     va_start( argp, fmt );
-#if defined(_TRUNCATE)
+#if defined(_TRUNCATE) && !defined(__MINGW32__)
     ret = _vsnprintf_s( s, n, _TRUNCATE, fmt, argp );
 #else
     ret = _vsnprintf( s, n, fmt, argp );
-- 
2.1.4


From a56ea243895426baa2eb76bddbbea604a076ab16 Mon Sep 17 00:00:00 2001
From: Thomas Glanzmann <thomas@glanzmann.de>
Date: Thu, 7 Jan 2016 11:14:59 +0100
Subject: [PATCH] Unbreak make install for mingw32

---
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 0950e6b..a41f52d 100644
--- a/Makefile
+++ b/Makefile
@@ -20,7 +20,7 @@ tests: lib
 	$(MAKE) -C tests
 
 ifndef WINDOWS
-install: no_test
+install: lib
 	mkdir -p $(DESTDIR)/include/mbedtls
 	cp -r include/mbedtls $(DESTDIR)/include
 	
-- 
2.1.4

**Comment by RonEld** [comment] 2017-09-06 14:58
Hi @sithglan I have made a PR in https://github.com/ARMmbed/mbedtls/pull/1079 according to your patch, but since I don't have the right environment, I would be happy if you could confirm

**Closed** 2018-03-11 08:30 UTC
Labels: CLA valid, bug, closed_in_jira, fix available, mirrored
