### ISSUE TITLE
An encoding tag problem of mbedtls_x509write_crt_der

### ISSUE THREAD

**Issue by raprepo** [ARMmbed/mbedtls#1860] opened 2018-07-13 05:54 UTC
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

When the **subject_name** or **issuer_name** contains non-ASCII printable characters (such as Chinese, Japanese, Russian, etc.), the certificate content output by **mbedtls_x509write_crt_der** will have some problems.

This problem can be replay with **cert_write** program. 
Just set `subject_name=CN=Cert,O=中文汉字,C=UK`

When the program runs successfully, the certificate can be generated, but when you view the contents of the certificate, you can find that the contents of the subject and/or issuer are not correct.

After debugging, I found the problem appeared here.

**mbedtls_x509write_crt_der**()
-> **mbedtls_x509_write_names**()
-> **x509_write_name**()
-> **mbedtls_asn1_write_printable_string**():
`MBEDTLS_ASN1_CHK_ADD( len, mbedtls_asn1_write_tag( p, start, MBEDTLS_ASN1_PRINTABLE_STRING ) );`

When I replace `MBEDTLS_ASN1_PRINTABLE_STRING` with `MBEDTLS_ASN1_UTF8_STRING`, there is no problem.

This seems to be due to the use of the wrong TAG, which causes the system cannot decode the certificate content properly.

**Comment by RonEld** [comment] 2018-07-15 10:43
@raprepo Thank you for reporting this issue!
I believe this is a duplicate of https://github.com/ARMmbed/mbedtls/issues/468
Please confirm

**Comment by ciarmcom** [comment] 2018-09-12 11:55
ARM Internal Ref: IOTSSL-2521

**Comment by hanno-arm** [comment] 2018-11-08 14:12
Fixed through PR #1641.

**Closed by hanno-arm** 2018-11-08 14:12 UTC
Labels: bug, component: X.509, fix available, mirrored, tracking
