### ISSUE TITLE
multiple/chained certificates issue

### ISSUE THREAD

**Issue by shkant** [ARMmbed/mbedtls#703] opened 2016-11-29 12:49 UTC
Hi,
I am implementing server and multiple clients having each client a separate certificate. I am using mbedtls-2.3.0 on windows Qt Creator 2.6.0.
On server-side: I am using the sequence as mentioned in ssl_cert_test.c
currently I am testing it with making "MAX_CLIENT_CERTS 1"
On Client-side: As mention in ssl_client1.c
But I am facing following issue during handshake on server side 
Performing the SSL/
TLS handshake
..\mbedtls-2.3.0\library\ssl_srv.c:1831: got ciphersuites in common, but none of
 them usable
Attached log is with debug level 1.
Please help me know where could be the issue, in generated certificates or in loading the certificates.
 let me know if any further information required to help me.
Regards,
Shashi
[client_log.txt](https://github.com/ARMmbed/mbedtls/files/618951/client_log.txt)
[Server_log.txt](https://github.com/ARMmbed/mbedtls/files/618950/Server_log.txt)

**Comment by sbutcher-arm** [comment] 2016-12-14 17:29
Hi! And thank you for the interest in mbed TLS!

This isn't actually a bug, but a support issue where I think you need help debugging your code. We recommend this kind of issue should be posted to the [mbed TLS forum](https://tls.mbed.org/discussions), where the community can help you.

Quickly looking at your logs, all I can say is what the debug already indicates - there's a mismatch between the configured cipher suites on both sides. The two ends are unable to communicate because there is no acceptable and common set of configured cipher suites. All I can recommend is you look closely at the configurations on both sides.

Given this is not a bug, I'm closing this issue.

**Closed by sbutcher-arm** 2016-12-14 17:29 UTC
Labels: question
