### ISSUE TITLE
Support of sign/verify for Edwards curve (MBEDTLS_ECP_DP_CURVE25519)

### ISSUE THREAD

**Issue by meghaamity** [ARMmbed/mbedtls#2067] opened 2018-10-08 11:16 UTC
### Description
- Type: Enhancement\Feature Request
- Priority: Blocker

## Enhancement\Feature Request
Edwards-Curve Digital Signature Algorithm for Curve25519.
mbedtls_Ecdsa_verify returns error if Curve25519 is used.
Which API to use for sign generation/verification 

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by RonEld** [comment] 2018-10-08 11:48
@meghaamity Thank you for your query
Mbed TLS does not support at the moment Edwards 25519 curve, for signing and verifying, hence the failure you are receiving.

Note that the Montgomery curve is used for ECDH, while Edwards is used for sign\verify.

**Comment by meghaamity** [comment] 2018-10-08 11:50
I need Edwards sign\verify as per RFC 8032.It is not present as if now.
By when will it be available?

**Comment by RonEld** [comment] 2018-10-08 12:00
@meghaamity We don't publicly publish our roadmap, so unfortunately I can't update when and if it will be supported. We will take into consideration your requirements.

**Comment by RonEld** [comment] 2018-10-08 13:11
Note that this is a duplicate of #388 hence closing this issue

**Closed by RonEld** 2018-10-08 13:11 UTC
Labels: component: Crypto, enhancement

**Comment by meghaamity** [comment] 2018-10-09 10:48
Hello Ron,
#388 issue is very old.Can you please consider this request as urgent.

Thanks a lot

**Comment by zhang-wenchao** [comment] 2018-11-04 07:30
@meghaamity Many people really need this feature, please consider support, thank you
