### ISSUE TITLE
1.3.10 / master on Ubuntu 15.04: getrandom_wrapper() fails with Function not implemented (38)

### ISSUE THREAD

**Issue by syzzer** [ARMmbed/mbedtls#191] opened 2015-04-27 17:10 UTC
When using mbed TLS 1.3.10 or the current mbedtls-1.3 branch on Ubuntu 15.04, mbed TLS attempts to use the getrandom syscall to retrieve random. That fails with errno 38: Function not implemented. There is currently no way to control this behaviour through cmake, config.h, or from the application.

**Comment by mpg** [comment] 2015-04-29 00:02
Thanks for your report.

The issue is that, at compile-time, it looks like the `getrandom()` syscall is available, since its syscall number is defined in `unistd.h`, but at runtime a kernel older than 3.17 is used. We'll probably move to runtime detection of the kernel version using uname(2) to avoid this issue.

**Comment by mpg** [comment] 2015-04-29 12:32
This should be fixed by this commit: https://github.com/ARMmbed/mbedtls/commit/d97828e7afbc7c3bc5824083f79a2a6a73bc2420

If you can get test it on your machine and confirm if it works, that would be greatly appreciated.

**Comment by mpg** [comment] 2015-04-29 15:14
I just tested the fix on an Arch machine with a recent `unistd.h` but an older (3.14) kernel, and it works for me.

**Closed by mpg** 2015-04-29 15:14 UTC

**Comment by syzzer** [comment] 2015-04-29 20:57
That was quick. Thanks! This indeed fixes the problem for me.

**Comment by mpg** [comment] 2015-04-30 07:58
Great! Thanks for testing it.
