### ISSUE TITLE
mbedTLS C library, error reporting for certificate files that are not yet valid by time... mbedtls_x509_crt_parse_file not validating time of file/system time

### ISSUE THREAD

**Issue by andrewhodel** [ARMmbed/mbedtls#4138] opened 2021-02-10 20:17 UTC
Latest version.

```
#include "mbedtls/net_sockets.h"
#include "mbedtls/debug.h"
#include "mbedtls/ssl.h"
#include "mbedtls/base64.h"
#include "mbedtls/sha1.h"
#include "mbedtls/entropy.h"
#include "mbedtls/ctr_drbg.h"
#include "mbedtls/error.h"
#include "mbedtls/certs.h"
```

```
  ! mbedtls_ssl_handshake returned -0x2700
```

```
		// load root CA certificate from root_cert_file which is provided as a ARGV parameter
		if ((ret = mbedtls_x509_crt_parse_file(&cacert, root_cert_file)) != 0) {
			mbedtls_printf(" failed\n  !  mbedtls_x509_crt_parse returned -0x%x\n\n", -ret);
			goto reconnect;
		}

		// tls/ssl handshake
		while ((ret = mbedtls_ssl_handshake(&ssl)) != 0) {
			if (ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE) {
				mbedtls_printf(" failed\n  ! mbedtls_ssl_handshake returned -0x%x\n\n", (unsigned int) -ret);
				goto reconnect;
			}
		}

```

The error is being returned with `mbedtls_ssl_handshake` and should be returned by `mbedtls_x509_crt_parse_file`.

**Comment by mpg** [comment] 2021-02-16 09:20
Hi @andrewhodel and thanks for your interest in Mbed TLS!

I understand that you find the behaviour of `mbedtls_x509_crt_parse_file()` surprising, but I think it's by design. In our X.509 API responsibilities are split: the parsing function just parses and only returns errors if the certificate was not syntactically correct, but does not perform any semantic check about validity. Then `mbedtls_x509_crt_verify()` takes care of checking validity.

Also, I agree that it's good to return errors early when we can, which is that case would mean at parse time. But unfortunately we can't really do that properly: we could check if the certificate looks acceptable _to us now_ but what matters is whether it looks acceptable _to our peer when we us it_ and that's not something we can determine locally. One can imagine all sorts of differences here, from our local clock not being in sync with that of  our peer, to our peer not checking the time at all, or even the certificate time-validity changing between the time we parse it and the time we use it...

Finally, I can imagine many reasons someone might want to load and use certificates that are not time-valid. If the parsing function returned an error at this point, it would make life more complicated for those use cases, while not making like that much easier in your use case (as argued in the previous paragraph).

For these reasons, I'm inclined to close this issue as "notabug", but before that I obviously want to give you a chance to respond to my points or clarify if I misunderstood your request, and I'll also ask a second team member to review.

**Comment by chris-jones-arm** [comment] 2021-02-16 10:03
I am going to agree with @mpg here. This looks like intended behaviour from the library and therefore "notabug" seems appropriate.

Please do let us know if we've both misunderstood however and we can re-open this.

**Comment by andrewhodel** [comment] 2021-02-16 16:06
How would the peer know the time on the local system?

If I have a set of ca certs and request a domain like google.com via TLS on port 443 it fails if the time isn’t set and works if the time is set. 

That isn’t the peer responding, that is the local code not accepting the certs if the timestamp of the file is later than the local time of the machine. 

I do not understand why this cannot be checked and provide an error message saying, “cert file has a later timestamp than the local machine time” on the initial parse and each query to the file in memory. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-16 16:53
At the root, changing the local machine time results in success or failure with the same ca file. 

The errors should mention the time being the problem, not be ambiguous. 

If a stat call each lookup is the concern, then you can only lookup the time when an error is raised. 


Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-16 16:53
﻿Regardless of if TLS sent the timestamp of a certificate, it would send the timestamp of the certificate not that of the local machine. 

In this case, the timestamp of the local machine is preventing validation, not the timestamp of the file. 

That in itself proves that the problem is with the local code validation, not that across the network. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-16 18:19
﻿Curl, wget, almost everything tests for a valid timestamp and local machine time. Is the real problem warning handlers in C and stderr having output without an exit code being normal “thinking” or are you building this with something other than libc/musl and the linux kernel?

At the very least, this should be checked when an error is raised and sent as a message to the error handler if the timestamp of the local machine is behind that of the certificate. 



Thank You,
Andrew Hodel

**Comment by gilles-peskine-arm** [comment] 2021-02-16 18:30
> the certificate time-validity changing between the time we parse it and the time we use it...

I suspect that this is moderately common on embedded systems that load a certificate early during boot, before setting the clock.

**Comment by andrewhodel** [comment] 2021-02-16 19:33
Check on error. 

Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-17 00:52
That wouldn’t affect systems that load the certs before setting the time, and would inform developers who are troubleshooting a problem of an issue. 

Only requiring a file stat in the error function. 



Thank You,
Andrew Hodel

**Comment by gilles-peskine-arm** [comment] 2021-02-17 10:05
> Only requiring a file stat in the error function.

I can't think of anything that I would call an “error function” that has access to a file.

Please keep in mind that Mbed TLS is a C library primarily intended for embedded systems. It doesn't pass around large objects from which all related objects are accessible. For example, an error is just a numeric code, not an exception object to which other objects can be attached arbitrarily.

**Comment by mpg** [comment] 2021-02-17 12:01
> That isn’t the peer responding, that is the local code not accepting the certs if the timestamp of the file is later than the local time of the machine.

Sorry, I misread that part of your report: I though you were loading a client cert, but actually you are loading trust anchors (CAs). So indeed the verification happens on the local machine with its local time.

Unfortunately, this doesn't really change the situation that much: the certificate needs to be valid at the time it is used, so time validity needs to be checked by `mbedtls_x509_crt_verify()` anyway. And there could be any interval of time between the moment `parse()` is called and the moment `verify()` is called (think a long-running process that only loads trust anchors at start-up, or an embedded device that only loads them at boot and could run for months between reboots).

Actually, some stores of trust anchors (such as the ca-certificates package present in several Linux distributions) tend to handle rotations by shipping both the old and the new certs, so it's fully expected that when we parse that collection of certificates, one of them will be either expired or not-valid-yet. (Then `verify()` does the right thing and selects the root that is currently valid, we had a feature request for that a long time ago.) This would break if `mbedtls_x509_crt_parse()` started checking time-validity and returning errors about it.

> The errors should mention the time being the problem, not be ambiguous.

I think the error already reflects that. If the trusted root is not-yet-valid but the chain is otherwise correct, the `flags` argument of `mbedtls_x509_crt_verify()` will be set to `MBEDTLS_X509_BADCERT_FUTURE` which quite unambiguously indicates that time is the problem here. After a (failed) handshake, you can get those flags with `mbedtls_ssl_get_verify_result()` and convert them to human-readable string using `mbedtls_x509_crt_verify_info()` - in that case, "The certificate validity starts in the future".

> At the very least, this should be checked when an error is raised and sent as a message to the error handler if the timestamp of the local machine is behind that of the certificate.

I think that's pretty much what happens: a flag is set to indicate that the reason for the rejecting the certificate is that its validity period starts in the future (according to the local clock).

**Comment by andrewhodel** [comment] 2021-02-17 14:26
@mpg 

you think this error message tells people that the timestamp of the ca file or local machine time is the problem:

mbedtls_ssl_handshake returned -0x2700

Did you not read in the original post that:

The error is being returned with mbedtls_ssl_handshake and should be returned by mbedtls_x509_crt_parse_file.

what you are saying is, when there is a handshake error that every program that uses mbedtls should call another function, why doesn’t that happen automatically?

what I am trying to explain is that, you can do this by default when there is an error and help every developer that uses this library. Why on earth would you make it more difficult, it isn’t documented in the handshake function documentation or code either. 

That is only the first problem, the second problem is that the timestamp of the CA file and system time are not validated against one another when the parse file function is initially called. 

None of what you are saying does anything but cloud the understanding. Why don’t you make it better and fix these two things:

* ssl_handshake function automatically checks for ca file timestamp vs local machine time errors
* parse_file function checks for ca file timestamp vs local machine time errors


Please explain without paragraphs of other functions, why these things don’t happen in a way that makes your library less work to the developers.

**Comment by andrewhodel** [comment] 2021-02-17 14:30
Currently I am without a keyboard with the power outages, if this is this complicated for adding timestamp checking and reporting to two functions, I will just open another issue and keep it strict and simple when electricity returns. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-17 16:02
Unfortunately, this doesn't really change the situation that much: the certificate needs to be valid at the time it is used, so time validity needs to be checked by mbedtls_x509_crt_verify() anyway. And there could be any interval of time between the moment parse() is called and the moment verify() is called (think a long-running process that only loads trust anchors at start-up, or an embedded device that only loads them at boot and could run for months between reboots).

That is not a valid reason to not check in the verify() function, it is actually important to check so the administrator doesn’t accept everything as working for programs that open sockets later. 

It is also needed that an error from a handshake would go through and check of the certificate file was out of date. This would make more sense as it would take less developer time to implement this library if all the things that could be wrong were checked and reported on an error condition. The developer should not have to type put each error check function when an error is raised. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-17 16:50
I can understand why it wouldn’t want to exit with code 1+N when the parse file function finds the ca file out of date. Many embedded systems without anything but time since boot. I cannot understand why it wouldn’t warn though, if a local time existed. 

In regards to a handshake failure. I cannot understand why the base error function would not check all of these possible mishaps and report the status of each simply to help get things back normal as soon as possible. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-17 16:51
﻿I can understand why it wouldn’t want to exit with code 1+N when the parse file function finds the ca file out of date. Many embedded systems without anything but time since boot. I cannot understand why it wouldn’t warn though, if a local time existed. 

In regards to a handshake failure. I cannot understand why the base error function would not check all of these possible mishaps and report the status of each simply to help get things back normal as soon as possible. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-17 16:55
Is mbedtls_printf not a function? Perhaps it would be better understood if I called it an error routine. 

I do not understand why mbedtls_printf wouldn’t have an error counterpart that has a routine within the function to check all the return values and their bitmasks to tell the developer of the actual problem. Why would you expect this to be written into every program that uses your library?



Thank You,
Andrew Hodel

**Comment by gilles-peskine-arm** [comment] 2021-02-17 17:24
`mbedtls_printf` just prints strings, it's unrelated to errors. Did you mean `mbedtls_strerror`? That function has to work with what it's given, which is a numeric error code. It doesn't have any information about the cause of the error.

I have trouble understanding what you want, but I suspect that it's `mbedtls_ssl_get_verify_result`.

> Return the result of the certificate verification
> (…)
> Return: A bitwise combination of `MBEDTLS_X509_BADCERT_XXX` and `MBEDTLS_X509_BADCRL_XXX` failure flags; see `x509.h`.

**Comment by gilles-peskine-arm** [comment] 2021-02-17 17:25
I'm closing this issue because it does not appear to be either a bug report or a feature request.

**Closed by gilles-peskine-arm** 2021-02-17 17:25 UTC
Labels: Community, notabug

**Comment by andrewhodel** [comment] 2021-02-17 20:25
Then why on earth would your examples on the mbed website that everyone who uses your library starts with only have the error checking and reporting that I posted at the origin of this thread?

Can you fix that please, I am just trying to help you realize these prohibitors to success. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-17 20:27
Also, a bitwise return doesn’t make any sense without a function to print a sane string!

I will go back and rewrite all this and change the date then open as issue as to how it can be improved when I regain keyboard access. 

Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment] 2021-02-17 21:27
> I'm closing this issue because it does not appear to be either a bug report or a feature request.

Asking for a function to return more than an integer is a feature, there is a printf function in the library so strings are supported.
