### ISSUE TITLE
Unresolved symbols Visual Studio 14 2015 ARM

### ISSUE THREAD

**Issue by gatkinso** [ARMmbed/mbedtls#735] opened 2017-01-04 13:11 UTC
Attempting to build with
 
    > cmake -G "Visual Studio 14 2015 ARM" ..

results in following linker errors:

mbedcrypto.lib(entropy_poll.obj) : error LNK2019: unresolved external symbol __imp_CryptAcquireContextA referenced in function mbedtls_platform_entropy_poll [F:\work\mbedtls\build\programs\pkey\dh_server.vcxproj]

mbedcrypto.lib(entropy_poll.obj) : error LNK2019: unresolved external symbol __imp_CryptReleaseContext referenced in function mbedtls_platform_entropy_poll [F:\work\mbedtls\build\programs\pkey\dh_server.vcxproj]

mbedcrypto.lib(entropy_poll.obj) : error LNK2019: unresolved external symbol __imp_CryptGenRandom referenced in function mbedtls_platform_entropy_poll [F:\home\geoffrey\work\mbedtls\build\programs\pkey\dh_server.vcxproj]

F:\work\mbedtls\build\programs\pkey\Debug\dh_server.exe : fatal error LNK1120: 3 unresolved externals [F:\work\mbedtls\build\programs\pkey\dh_server.vcxproj]

**Comment by gatkinso** [comment] 2017-01-05 12:20
Looks like it is simply missing a link specifier for advapi32.

**Comment by ciarmcom** [comment] 2017-05-13 23:50
ARM Internal Ref: IOTSSL-1389

**Comment by sbutcher-arm** [comment] 2017-10-02 23:05
@RonEld - I went to merge this, but found I couldn't reproduce the original fault. Windows 7, plus Visual Studio 2015 or 2017 (I tried both), and the library builds without warnings.

Were you able to reproduce the fault?

**Comment by sbutcher-arm** [comment] 2017-10-07 22:39
As stated in #746, the fix is trivial. The library seems to work for us out of the box, and we (or I) can't reproduce the error. The fix itself is probably harmless, but I'd like to understand what the issue is before we merge. Because we can't reproduce the problem, I'm closing the PR and issue.

@gatkinso - (or anyone else!) - If this is still a problem for you, please feel free to reopen the issue - but please let us know how to reproduce the issue! Thanks.

**Closed by sbutcher-arm** 2017-10-07 22:39 UTC
Labels: bug, fix available, mirrored, tracking
