### ISSUE TITLE
21 tests in test_suite_x509parse fail when MBEDTLS_HAVE_TIME_DATE not defined

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1264] opened 2018-01-09 13:52 UTC
### Description
- Type: Bug
- Priority:  Major
raised by Trinity in the [support forum](https://tls.mbed.org/discussions/bug-report-issues/testsuite-using-time-and-date-information)
---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: development
OS version: Ubuntu16.04
Configuration: `MBEDTLS_HAVE_TIME_DATE` undefined

**Expected behavior**   
tests to pass, or skipped if depend on undefined configuration
**Actual behavior**  
21 tests fail

**Steps to reproduce**  
undefine `MBEDTLS_HAVE_TIME_DATE`
compile
run ./test_suite_x509parse

Note: need to add depends:MBEDTLS_HAVE_TIME_DATE to these failed test cases ( all of the failures happen on future\past and revoked certificates)

**Comment by ciarmcom** [comment] 2018-01-09 16:51
ARM Internal Ref: IOTSSL-2001

**Comment by sbutcher-arm** [comment] 2018-07-20 18:19
This is a duplicate of issue #1475 which has now been fixed in PR #701.

**Closed by sbutcher-arm** 2018-07-20 18:19 UTC
Labels: bug, mirrored, tracking
