### ISSUE TITLE
handshake error -0x50 - NET - Connection was reset by peer

### ISSUE THREAD

**Issue by salugoju** [ARMmbed/mbedtls#5289] opened 2021-12-08 18:07 UTC
### Summary
I am trying to encrypt data. On the server end I am using the openssl and on the client end I cant use openssl but I can use mbedtls.
I am using mbedtls-2.26.0 version.

The certificate is generated via https://github.com/michaelklishin/tls-gen
The certificate is valid and has no issue .
The communication works fine when I use the ssl_client2 and ssl_server2 applications from the mbedtls-2.26.0\programs.
The communication works fine when I use the openssl client and openssl server. 
[All](`[url](url)`) the communication right now is localhost only. 

But when I try to use the openssl server and ssl_client2 from mbedtls-2.26.0\programs the connection is reset.
I think it’s a config issue but I am not able to figure out the solution or the root cause.
 
### System information

Mbed TLS version (number or commit id): 2.26.0
Operating system and version: windows 10
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Steps to reproduce
Below is the log from wireshark. Attached is the log from sslclient2 program.
After the certificate is verified the broker resets the connection 
TCP        60271 → 5671    [SYN] Seq=0 Win=65535 Len=0 MSS=65475 WS=256 SACK_PERM=1
TCP        5671 → 60271    [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0 MSS=65475 WS=256 SACK_PERM=1
TCP        60271 → 5671    [ACK] Seq=1 Ack=1 Win=2618880 Len=0
TLSv1.2                Client Hello
TCP        5671 → 60271    [ACK] Seq=1 Ack=305 Win=2618880 Len=0
TLSv1.2                Server Hello, Certificate, Server Key Exchange, Certificate Request, Server Hello Done
TCP        60271 → 5671    [ACK] Seq=305 Ack=1976 Win=2616832 Len=0
TLSv1.2                Certificate
TCP        5671 → 60271    [ACK] Seq=1976 Ack=945 Win=2618112 Len=0
TLSv1.2                Client Key Exchange
TCP        5671 → 60271    [ACK] Seq=1976 Ack=1088 Win=2618112 Len=0
TLSv1.2                 Certificate Verify
TCP        5671 → 60271    [ACK] Seq=1976 Ack=1173 Win=2618112 Len=0
TLSv1.2                 Change Cipher Spec
TCP        5671 → 60271    [ACK] Seq=1976 Ack=1179 Win=2618112 Len=0
TLSv1.2                 Encrypted Handshake Message
TCP        5671 → 60271    [ACK] Seq=1976 Ack=1216 Win=2617856 Len=0
TLSv1.2                 Change Cipher Spec, Encrypted Handshake Message
TCP        60271 → 5671    [ACK] Seq=1216 Ack=2019 Win=2616832 Len=0
TLSv1.2                 Application Data
TCP        5671 → 60271    [ACK] Seq=2019 Ack=1245 Win=2617856 Len=0
TLSv1.2                 Application Data
TCP        60271 → 5671    [ACK] Seq=1245 Ack=2048 Win=2616832 Len=0
TLSv1.2                 Encrypted Alert
TCP        60271 → 5671    [ACK] Seq=1245 Ack=2071 Win=2616832 Len=0
TCP        5671 → 60271    [RST, ACK] Seq=2071 Ack=1245 Win=0 Len=0

### Additional information

I am not sure if I can use mbedtls client with openssl server.
Could you please help me understand the issue in this setup.

**Comment by gilles-peskine-arm** [comment] 2021-12-08 18:42
You can use an Mbed TLS client with an OpenSSL server or vice versa. And I think that your test shows that it is in fact working.

In the transcript you posted, we can see that the handshake completes successfully, and some application data is exchanged in both directions. Then the server closes the connection. So this isn't a certificate or configuration negotiation problem.

In terms of data exchanged over the connection, `ssl_client2` and `openssl s_server` are simple test programs. `ssl_client2` is compatible with `openssl s_server -www` (it's what we use for interoperability testing). If you're passing some different data as input to `openssl s_server`, it may want to close the connection while `ssl_client2` is still expecting data.

If this doesn't help, please let us know **exactly** what commands you're running and attach any test files (certificates, keys, etc.) that you're using.

**Comment by salugoju** [comment] 2021-12-08 19:52
[mbedclientrmqserver_reconect.txt](https://github.com/ARMmbed/mbedtls/files/7678495/mbedclientrmqserver_reconect.txt)

Hi ,

Thank you for confirmation. yes the handshake completes and the data is exchanged in both directions. but then server closes the connection. If I change the opt.reconnect to non zero it does reconnect and the handshake is successful. But then again it is reset. How can i prevent this reset? 
The openssl server in this case is my RabbitMQ broker. 
Is the issue is on client end data only?
Or the broker?

Thank you for quick reply.

**Comment by gilles-peskine-arm** [comment] 2021-12-08 20:06
`ssl_client2` is a test program. It doesn't speak AMQP. It's just sending data that RabbitMQ doesn't understand. The TLS part of the communication is going well. The server receives something that looks like an HTTP request, because that's what `ssl_client2` sends. Since this request is not a valid request for RabbitMQ, it closes the connection. This is perfectly normal.

To talk to RabbitMQ, you need to write or use a program that speaks a protocol that RabbitMQ understands. Mbed TLS implements the TLS level of communication. The data that is sent over TLS is your responsibility.

**Comment by gilles-peskine-arm** [comment] 2021-12-08 20:08
I am closing this issue because Mbed TLS is working normally. The problem is at the application protocol level.

**Closed by gilles-peskine-arm** 2021-12-08 20:08 UTC
