### ISSUE TITLE
mbedtls 2.3.0 fails to compile: error unknown type name

### ISSUE THREAD

**Issue by edsiper** [ARMmbed/mbedtls#527] opened 2016-07-04 14:52 UTC
Trying to upgrade mbedtls from 2.2.1 to 2.3.0 we found it's not compiling:

```
In file included from /home/edsiper/tmp/monkey-1.6.9/plugins/tls/../../deps/mbedtls-2.3.0/include/mbedtls/net.h:32:0,
                 from /home/edsiper/tmp/monkey-1.6.9/plugins/tls/tls.c:35:
/home/edsiper/tmp/monkey-1.6.9/plugins/tls/../../deps/mbedtls-2.3.0/include/mbedtls/ssl.h:545:5: error: unknown type name ‘mbedtls_time_t’
     mbedtls_time_t start;       /*!< starting time      */
     ^
In file included from /home/edsiper/tmp/monkey-1.6.9/plugins/tls/tls.c:42:0:
/home/edsiper/tmp/monkey-1.6.9/plugins/tls/../../deps/mbedtls-2.3.0/include/mbedtls/ssl_cache.h:63:5: error: unknown type name ‘mbedtls_time_t’
     mbedtls_time_t timestamp;           /*!< entry timestamp    */
     ^
```

The version used is the provided one by the project site under Apache license.

**Comment by ciarmcom** [comment] 2016-07-04 15:51
ARM Internal Ref: IOTSSL-851

**Comment by jcowgill** [comment] 2016-07-04 17:11
This is a duplicate of #522

**Comment by sbutcher-arm** [comment] 2016-07-14 14:37
Hi @edsiper,

As @jcowgill says, this is a duplicate of #522, which is now fixed. If you want to pick up a fixed version, please use either the tag `yotta-2.3.2` or commit 4dcae42.

Apologies for breaking your code. We really should have done better and caught this bug before shipping.

The next release to contain this fix will be our next formal mbed TLS release, due later in Q3 although we have no public date yet.

**Closed by sbutcher-arm** 2016-07-14 14:37 UTC
Labels: bug, mirrored
