### ISSUE TITLE
embedtls does not work with clang 13 optimization -O2

### ISSUE THREAD

**Issue by weidonglian** [ARMmbed/mbedtls#5171] opened 2021-11-15 14:34 UTC
### Summary

I am running embedtls 2.xx on clang 13 -O2 compiler flag. 

### System information

Mbed TLS version (number or commit id): 2.xx
Operating system and version: Both Linux, MAC, iOS and Android with clang 13. 
Configuration (if not default, please attach `mbedtls_config.h`): default. 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Clang 13 with -O2
Additional environment information: 

### Expected behavior

embedtls should work with clang 13

### Actual behavior

 `    int res = mbedtls_ssl_handshake(&ssl);` fails all the time. 

### Additional

I have tried 3.00 latest version, it does not work either. However, if I try the current development, it works. However, the embedtls development version requires code generation which is not possible for our build system. 

I am wondering if possible to make a new release of the current development version, since clang-13 is widely used on iOS development now with new xcode.

**Comment by codeservice** [comment] 2021-11-15 19:20
I can confirm this issue related to [#5152](https://github.com/ARMmbed/mbedtls/issues/5152)
I tried compile MBED without flag -O2 and handshake works correctly

**Comment by weidonglian** [comment] 2021-11-16 08:18
Is there any potential patch?

**Comment by gilles-peskine-arm** [comment] 2021-11-16 09:04
This is a known issue which is fixed in the [`development`](https://github.com/ARMmbed/mbedtls/tree/development) (future 3.1) and [`development_2.x`](https://github.com/ARMmbed/mbedtls/tree/development_2.x) (future 2.28) branches, at least for at least for x86_64 and arm64 architectures. The bug is in some assembly code and may still be present on other architectures, including perhaps some arm variants. What exact platform are you compiling for?

**Comment by weidonglian** [comment] 2021-11-16 09:33
> This is a known issue which is fixed in the [`development`](https://github.com/ARMmbed/mbedtls/tree/development) (future 3.1) and [`development_2.x`](https://github.com/ARMmbed/mbedtls/tree/development_2.x) (future 2.28) branches, at least for at least for x86_64 and arm64 architectures. The bug is in some assembly code and may still be present on other architectures, including perhaps some arm variants. What exact CPU are you compiling for?

ARM and X86. 
I think your fix is good enough for me and I am using 2.26 and I just need a patch to fix it for now and then in the future I could upgrade to 2.28 or 3.xxx. 

Is this https://github.com/ARMmbed/mbedtls/pull/4947/files the patch? 
Thanks in advance. 
BR
Weidong

**Comment by weidonglian** [comment] 2021-11-16 10:02
To whom that suffers the same issue: 
I am using 2.26 and I patch with: 
1. https://github.com/ARMmbed/mbedtls/pull/4947/files
2. https://github.com/ARMmbed/mbedtls/commit/a23be2230845847df46c98a8ae54e18313de2dc4#diff-b0c728c62ee1a275964b834bb62b87ba136342bdf909bdc2a2b854bf062e3233

Now it works nicely! maybe I also need to patch more for other CPU arches, so far it works for amd64 and arm64.

**Comment by gilles-peskine-arm** [comment] 2021-11-16 10:06
The patch for x86_64 is #4947. The patch for arm64 is #4968. The bug is likely present on some other architectures, we have a [backlog task to review and fix other architectures](https://github.com/ARMmbed/mbedtls/issues/4943).

**Comment by mpg** [comment] 2021-11-16 10:18
Note: another workaround, if local patching is not acceptable, is to disable `MBEDTLS_HAVE_ASM` in `mbedtls_config.h`. It might decrease performance, though.

**Comment by weidonglian** [comment] 2021-11-16 10:45
> The patch for x86_64 is #4947. The patch for arm64 is #4968. The bug is likely present on some other architectures, we have a [backlog task to review and fix other architectures](https://github.com/ARMmbed/mbedtls/issues/4943).

@gilles-peskine-arm  thanks for your confirmation.

**Comment by davidhorstmann-arm** [comment] 2021-11-23 11:47
Closing as duplicate of #4116 and friends. See #4943 for more details

**Closed by davidhorstmann-arm** 2021-11-23 11:47 UTC
Labels: bug, Product Backlog, Community
