### ISSUE TITLE
Problem with errno and fcntl

### ISSUE THREAD

**Issue by nkolban** [ARMmbed/mbedtls#845] opened 2017-03-13 05:05 UTC
If we look at the following code, we see that it checks errno ... however I think there is a problem ...

https://github.com/ARMmbed/mbedtls/blob/master/library/net_sockets.c#L278

What we want to check is errno's value when the function is called.  However, what I think we are checking is the errno value from the last fcntl is the same function.

**Comment by ciarmcom** [comment] 2017-04-10 11:51
ARM Internal Ref: IOTSSL-1324

**Comment by RonEld** [comment] 2017-09-10 13:13
duplicate of #733

**Closed** 2017-11-29 20:12 UTC
Labels: bug, fix available, mirrored, tracking
