### ISSUE TITLE
Certificate with invalid signature returning no error

### ISSUE THREAD

**Issue by JohnJosef** [ARMmbed/mbedtls#2908] opened 2019-10-29 09:43 UTC
### Description
- Type: Question
- Priority: Blocker
---------------------------------------------------------------
## Question

I have a certificate with invalid signature (a certificate which is manually modified)
 - Version 2.16.0 : When a certificate with invalid signature is sent to API mbedtls_x509_crt_verify_with_profile, it returns zero.
 
 - Version 2.8.0 : The API mbedtls_x509_crt_verify_with_profile returns error (Error : -9984) when the same certificate is passed
 
 - Is there any other API which does check if the certifcate has an invalid signature?

 - What is the reason for different return values in these versions?

**mbed TLS build:**  
Version: 2.8.0
Version: 2.16.0
OS version: Ubuntu 18.04.3

**Comment by RonEld** [comment] 2019-10-31 12:04
HI @JohnJosef 
Your description sounds like there might be a bug introduced to the library, however I would like to see the logs and the certificate in order to conclude this.
Could you please share the invalid certificate?

**Comment by JohnJosef** [comment] 2019-11-05 07:21
> 
> 
> HI @JohnJosef
> Your description sounds like there might be a bug introduced to the library, however I would like to see the logs and the certificate in order to conclude this.
> Could you please share the invalid certificate?

Hi @RonEld 
Thanks for the response.

I can share the certificate but I am bound with some confidentiality clauses which restricts me from sharing the certificate in public. Is there a way I can share the certificate privately with you?

**Comment by gilles-peskine-arm** [comment] 2019-11-19 17:12
Hi @JohnJosef , please send us an email at support.mbedtls@arm.com.

**Comment by Wooodys** [comment] 2020-09-15 08:15
H @gilles-peskine-arm i, 
can you confirm that this behavior is a bug or wanted. And is it fixed in the newer versions?

**Comment by gilles-peskine-arm** [comment] 2020-09-15 08:33
@Wooodys If a certificate is valid but `mbedtls_x509_crt_verify_with_profile`, this is definitely a bug.

Without an example of a problematic certificate, I can't tell you whether there is actually a bug, and if so whether this bug has been fixed. [There have been several bug fixes in X.509 certificate parsing and verification since 2.16.0](https://raw.githubusercontent.com/ARMmbed/mbedtls/development/ChangeLog).

**Comment by gilles-peskine-arm** [comment] 2020-09-15 08:34
I'm closing this issue because although it may be a bug, there is no way to reproduce it, and we would not be able to tell whether we've fixed it.

**Closed by gilles-peskine-arm** 2020-09-15 08:34 UTC
Labels: question

**Comment by Wooodys** [comment] 2020-09-15 08:47
@gilles-peskine-arm I attached a cerificate with an invalid signiture that passes mbedtls_x509_crt_verify_with_profile on version 2.24.0 so you can reproduce the behavior.
[test.zip](https://github.com/ARMmbed/mbedtls/files/5223629/test.zip)
