### ISSUE TITLE
ssl_msg.c:1168:5: error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by reddy-quan** [ARMmbed/mbedtls#3901] opened 2020-11-20 08:15 UTC
### Description
- Type: Bug
- Priority:  Minor
---------------------------------------------------------------
## Bug
Directly build mbedtls with “make" I met the following errors, I have moved the define of i out of 'for' state to make it success. I think this should be fixed to make it not easy to make such mistakes.
1.
```
ssl_msg.c: In function ‘mbedtls_ssl_cf_memcpy_if_eq’:
ssl_msg.c:1168:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < len; i++ )
     ^
ssl_msg.c:1168:5: note: use option -std=c99 or -std=gnu99 to compile your code
  CC    ssl_tls.c
make[1]: *** [ssl_msg.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [lib] Error 2
```
2.
```
suites/test_suite_psa_crypto.function: In function ‘test_mac_sign’:
suites/test_suite_psa_crypto.function:3068:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < ARRAY_LENGTH( output_sizes_to_test ); i++ )
     ^
suites/test_suite_psa_crypto.function:3068:5: note: use option -std=c99 or -std=gnu99 to compile your code
suites/test_suite_psa_crypto.function: In function ‘test_mac_verify’:
suites/test_suite_psa_crypto.function:3162:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < expected_mac->len; i++ )
     ^
make[1]: *** [test_suite_psa_crypto] Error 1
make: *** [tests] Error 2
```
3.
```
suites/test_suite_psa_crypto.function: In function ‘test_mac_verify’:
suites/test_suite_psa_crypto.function:3163:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < expected_mac->len; i++ )
     ^
suites/test_suite_psa_crypto.function:3163:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [test_suite_psa_crypto] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [tests] Error 2
```
4.
```
ssl_msg.c: In function ‘mbedtls_ssl_cf_memcpy_if_eq’:
ssl_msg.c:1168:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < len; i++ )
     ^
ssl_msg.c:1168:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [ssl_msg.o] Error 1
make: *** [lib] Error 2
```

**mbed TLS build:**  
Version: 406a5da4ab9983d6156ce537e4bfa8a8301ed7e1
OS version:Linux ubuntu6020 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)

Configuration: default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  NULL
Additional environment information:  NULL

**Comment by mpg** [comment] 2020-11-23 08:39
Hi @reddy-quan and thanks for you report. This happens to be a known issue: we made an explicit decision to start using C99 features in the development branch, but when making that decision we didn't immediately realise that some compiler versions still in use don't allow C99 by default, so unfortunately our `Makefile`s and `CMakeLists.txt`s haven't been adapted yet, see #3631. There's a PR pending for fixing this: #3641, which is pending review - if you'd like to have a look at and share your thoughts, that would be welcome.

In the meantime, a workaround is to pass appropriate flags to your compiler (as suggested by the compiler's error message) when invoking make. For example `CC='gcc --std=c99' make` should do the trick.

I'm closing this issue as a duplicate of #3631, and if you'd like to discuss this further, I invite you to continue the discussion on #3631.

**Closed by mpg** 2020-11-23 08:39 UTC

**Comment by WahyuAgungBudiyanto** [comment] 2022-03-09 06:18
what if i already had -lglu32 -lglut32 -lopengl32
