### ISSUE TITLE
Add accessor functions for "mbedtls_x509_crt" data structure for version 3.0

### ISSUE THREAD

**Issue by bbesharat** [ARMmbed/mbedtls#5173] opened 2021-11-15 21:09 UTC
### Suggested enhancement
Provide a function to access next field of mbedtls_x509_crt structure.
struct mbedtls_x509_crt * mbedtls_x509_crt_get_next();

### Justification
I pass next certificate in the CA-chain from mbedtls_x509_crt structure by accessing "next" field of this structure to "mbedtls_ssl_conf_ca_chain" function to set server certificate chain as follow:
        /* Set server certificate chain */
        mbedtls_ssl_config       conf; /* has been initialized and setup before this call */
        mbedtls_x509_crt         srvcert; /* has been initialized and setup before this call */
        mbedtls_ssl_conf_ca_chain(&conf, srvcert.next, NULL);

Mbed TLS needs this because 
Who ever tries to access any member of mbedtls_x509_crt structure would need accessor function to access its members in MbedTLS v3.x

**Comment by gabor-mezei-arm** [comment] 2021-11-16 11:58
This field is made public, no longer need an accessor function. Close as a duplicate of #5019.

**Closed by gabor-mezei-arm** 2021-11-16 11:58 UTC
Labels: enhancement, component: X.509, Community
