### ISSUE TITLE
DTLS example can not work on vs2010

### ISSUE THREAD

**Issue by Supowang** [ARMmbed/mbedtls#1199] opened 2017-12-06 06:14 UTC
I open the example Project in  mbedtls-2.6.0_server\visualc\VS2010，run dtls_client.exe and dtls_server.exe on my windows pc , I find the client can not connect to the server.

we should modify the mbedtls-2.6.0_server\programs\ssl\dtls-server.c 
line 173  " if( ( ret = mbedtls_net_bind( &listen_fd, NULL, "4433", MBEDTLS_NET_PROTO_UDP ) ) != 0 )" should be "    if( ( ret = mbedtls_net_bind( &listen_fd, "0.0.0.0", "4433", MBEDTLS_NET_PROTO_UDP ) ) != 0 )"
bind NULL cannot work .

**Comment by RonEld** [comment] 2017-12-06 09:45
Hi @Supowang Thank you for raising this issue. I believe this issue is a duplicate of #977 , therefore I am closing it. If you feel this issue was wrongfully closed, please reopen.

**Closed by RonEld** 2017-12-06 09:45 UTC

**Comment by Supowang** [comment] 2017-12-06 09:55
@RonEld  sorry  I have not see  the #997 issue before
Thanks a lot.
