### ISSUE TITLE
calculate hash of PK question

### ISSUE THREAD

**Issue by vtcao297** [ARMmbed/mbedtls#3003] opened 2020-01-23 00:48 UTC
Hopefully this should be a easy question to answer.

I have a X509 certificate that i want parse, and then calculate a hash of the Public Key (PK) in the certificate to compare it to a known hash value.  Since the PK is held in the mbedtls_pk_context struct, is it sufficient for me to some something like below (pseudo code) to calculate the hash of the PK?

mbedtls_x509_crt_init(&xCert);
mbedtls_x509_crt_parse(&xCert, xCert_ptr, xCert_size);
hash_type = MBEDTLS_MD_SHA384;
md_info = mbedtls_md_info_from_type(hash_type);
mbedtls_md(md_info, xCert.pk.pk_ctx, mbedtls_pk_get_len(&xCert.pk), md_hash);

**Comment by gilles-peskine-arm** [comment] 2020-01-23 09:16
Hi @vtcao297,

Hashing `pk.pk_ctx` is definitely wrong: this is the internal representation of the key. You're hashing a structure mostly containing pointers. You need `pk_raw`. I think something like this:
```
mbedtls_md(md_info, xCert.pk_raw.p, xCrt.pk_raw.len, md_hash);
```

**Comment by gilles-peskine-arm** [comment] 2021-04-23 13:43
I am closing this issue because it is an answered support request, not a bug report or an enhancement request.

**Closed by gilles-peskine-arm** 2021-04-23 13:43 UTC
Labels: question
