### ISSUE TITLE
Bug in SCSV

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbedtls#810] opened 2017-02-16 12:47 UTC
There seems to be a bug in SCSV. Since a few weeks (probably the grade changes in January), SSL Labs no longer reports that my webserver has SCSV support. They say it's due to an issue in mbed TLS. My bugreport to SSL Labs can be found [here](https://github.com/ssllabs/ssllabs-scan/issues/460).

I already sent this issue to Paul, but I heard he's no longer involved in mbed TLS development. He said he forwarded the issue to the current developers, but I like to be informed about the progress and hope to receive a patch.

**Comment by sbutcher-arm** [comment] 2017-02-16 12:50
Hi @hsleisink! Yes, @pjbakker, forwarded on the issue yesterday so we're aware of it and looking into it. 

Thanks for raising this with us.

**Comment by ciarmcom** [comment] 2017-02-16 12:50
ARM Internal Ref: IOTSSL-1223

**Comment by hsleisink** [comment] 2017-02-20 06:16
Is it possible to receive a patch for this issue? I want to release a new Hiawatha version and I want this issue to be fixed in this new release. Or can I wait for a new mbed TLS release? Thanks.

**Comment by andresag01** [comment] 2017-02-22 14:04
@hsleisink, thank you for raising this issue. I have read the discussion at https://github.com/ssllabs/ssllabs-scan/issues/460. As pointed out, the problem is that the mbed TLS server code at [library/ssl_srv.c](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_srv.c#L1710) does not check that TLS_FALLBACK_SCSV is the last element in the cipher suite vector of the ClientHello. Please note that the missing check is marked as SHOULD in [RFC7507 Section 4](https://tools.ietf.org/html/rfc7507#section-4). Furthermore, this recommendation is respected by mbed TLS clients as shown [here](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_cli.c#L904).

I have created [this PR](https://github.com/ARMmbed/mbedtls/pull/816) that addresses the issue.

**Comment by hsleisink** [comment] 2017-04-05 07:41
Any update about when this issue will be fixed in an official release?

**Comment by sbutcher-arm** [comment] 2017-04-20 10:18
Sorry for the late response @hsleisink. This will be included in the next quarterly release.

**Comment by sg-** [comment] 2017-06-05 15:21
Did this make it in the 2.5 release?

**Comment by sbutcher-arm** [comment] 2017-06-05 17:20
Hi @sg- 

This missed the `mbedTLS-2.5.0` release, but will be in `mbedTLS-2.5.1`.

**Comment by RonEld** [comment] 2018-07-29 12:35
Closing, as I believe this issue was fixed and merged in #924

**Closed by RonEld** 2018-07-29 12:35 UTC
Labels: bug, mirrored, tracking
