### ISSUE TITLE
timing-suite failed on s390x

### ISSUE THREAD

**Issue by mortenstevens** [ARMmbed/mbedtls#981] opened 2017-06-22 11:22 UTC
55: FAILED (0 / 1 tests (0 skipped))
55/60 Test #55: timing-suite .....................***Failed    6.76 sec
Timing selftest ................................................... 

Full buildlog: https://kojipkgs.fedoraproject.org//work/tasks/332/20080332/build.log

Any ideas how to fix this? This issue affects only the timing-suite on s390x.

**Comment by RonEld** [comment] 2017-06-22 11:59
Hi @mortenstevens I suggest you run the timing suite, with the verbose parameter, to have more information of the failure, for you to continue debugging:
~~~
./test_suite_timing --verbose
~~~

**Comment by mortenstevens** [comment] 2017-06-22 13:25
We are already using ctest --output-on-failure -V

**Comment by jcowgill** [comment] 2017-06-22 16:55
As a data point, mbedTLS succeeded building on s390x on Debian:
https://buildd.debian.org/status/fetch.php?pkg=mbedtls&arch=s390x&ver=2.5.1-1&stamp=1498131591&raw=0

**Comment by RonEld** [comment] 2017-06-22 17:09
@jcowgill Thanks for uploading the build report

@mortenstevens please run `./test_suite_timing --verbose` which will run the specific test_suite with output, which will be easier to debug, and not the full test_suite packages.
On successful run, the output should be:
~~~
./test_suite_timing --verbose
Timing selftest ...................................................   TIMING tests note: will take some time!
  TIMING test #1 (set_alarm / get_timer): passed
  TIMING test #2 (set/get_delay        ): passed
  TIMING test #3 (hardclock / get_timer): passed

PASS

----------------------------------------------------------------------------
~~~
We would like to focus on the specific test that fails

**Comment by ciarmcom** [comment] 2017-06-22 19:50
ARM Internal Ref: IOTSSL-1490

**Comment by mortenstevens** [comment] 2017-06-23 10:05
I think I'm not able to provide the requested information. As Fedora package maintainer we have only API access to Fedora build servers. So I can change only something like this:

**Comment by RonEld** [comment] 2017-06-25 08:17
Hi @mortenstevens 
please try the following changes:
in [*`tests/CMakeLists.txt`*](https://github.com/ARMmbed/mbedtls/blob/development/tests/CMakeLists.txt#L34) change
~~~
add_test(${data_name}-suite test_suite_${data_name})
~~~
to
~~~
add_test(${data_name}-suite test_suite_${data_name} --verbose)
~~~

after that, build the tests with debug:
~~~
cmake -D CMAKE_BUILD_TYPE=Debug .
~~~
and after that, run the test:
~~~
ctest -R timing-suite -V --debug
~~~
Is this something you can do?
I think this will show you at least what specific timing test fails

**Comment by mortenstevens** [comment] 2017-06-26 10:57
@RonEld 

Yes, thank you. It's strange. We are not able to reproduce this build issue. Maybe it was an issue related to our s390x build servers. Here is the output: 

Now, it's building fine:

https://kojipkgs.fedoraproject.org//work/tasks/3079/20183079/build.log

55: Test command: /builddir/build/BUILD/mbedtls-2.5.1/tests/test_suite_timing "--verbose"
/builddir/build/BUILD/cmake-3.8.2/Source/cmCTest.cxx:142    Current_Time: Jun 26 10:41 UTC
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:678 55: Test timeout computed to be: 9.99988e+06
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55: Timing selftest ...................................................   TIMING tests note: will take some time!
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55:   TIMING test #1 (set_alarm / get_timer): passed
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55:   TIMING test #2 (set/get_delay        ): passed
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55:   TIMING test #3 (hardclock / get_timer): passed
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55: 
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55: PASS
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55: 
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55: ----------------------------------------------------------------------------
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55: 
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:61 55: PASSED (1 / 1 tests (0 skipped))
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:703 1/
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:705 1 
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:721 Test
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:728  #55:
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:729  
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:761 timing-suite .....................
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:763 Testing timing-suite ... 
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:221    Passed  
/builddir/build/BUILD/cmake-3.8.2/Source/CTest/cmCTestRunTest.cxx:263   8.76 sec

**Comment by RonEld** [comment] 2017-06-26 11:02
@mortenstevens Thank you for your update
I'm glad this issue was probably resolved(although I still don't know exactly what was the root cause)
Please close this issue, if no further action required
Regards

**Comment by RonEld** [comment] 2017-09-06 12:08
We believe that this issue no longer exists, therefore closing it.
If you are not happy with this, please reopen

**Closed by RonEld** 2017-09-06 12:08 UTC
Labels: bug, mirrored, tracking
