### ISSUE TITLE
Fixed size buffer limits versatility

### ISSUE THREAD

**Issue by thomasknauth** [ARMmbed/mbedtls#1048] opened 2017-08-10 19:18 UTC
Using a fixed-size buffer here limits the size of certificates that can be created. In my particular use case I have a certificate with custom extensions that don't fit into the 2048 tmp_buffer. The size of tmp_buffer should be either enlarged or sized as a function of the input parameters.

https://github.com/ARMmbed/mbedtls/blob/5a1c0e716242acfc7027c78e36487f8df1786c83/library/x509write_crt.c#L305

**Comment by hanno-arm** [comment] 2017-08-10 19:35
Hi @thomasknauth,

thank you for raising this! We're already having a similar request for RSA keys (https://github.com/ARMmbed/mbedtls/issues/1019) and will look into these kinds of issues.

Regards,
Hanno

**Comment by ciarmcom** [comment] 2017-08-10 19:51
ARM Internal Ref: IOTSSL-1622

**Comment by RonEld** [comment] 2017-09-10 11:54
Hi @thomasknauth Since this issue is a duplicate of a previous issue, I am closing it. If you feel it was wrongfully closed, please reopen

**Closed by RonEld** 2017-09-10 11:54 UTC
Labels: enhancement, mirrored, tracking
