### ISSUE TITLE
add an mbedtls_platform_safer_memcmp() function

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1857] opened 2018-07-12 13:13 UTC
### Description
- Type: Enhancement\Feature Request
- Priority: Major

## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
Since more than one module needs a safer_memcmp function, it would be good to have such a function in `platform_utils` module.

**Suggested enhancement**  
migrate `mbedtls_ssl_safer_memcmp()` function from `ssl_internal.h()` to `platform_utils` and add tests.

**Comment by gilles-peskine-arm** [comment] 2020-09-15 16:37
We want to create a new library module for constant-flow code, to make it easier for both computers and humans to validate that code that should be constant-flow is indeed constant-flow. So I'm closing this as a duplicate of https://github.com/ARMmbed/mbedtls/issues/3649.

**Closed by gilles-peskine-arm** 2020-09-15 16:37 UTC
Labels: component: Platform, enhancement
