### ISSUE TITLE
Define process for updating Dockerfiles

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4639] opened 2021-06-10 11:47 UTC
Placeholder to track the work in:

https://github.com/ARMmbed/mbedtls-test/issues/165

so that we can accurately estimate the Q3 Tech Debt epic

**Comment by ronald-cron-arm** [comment] 2021-07-05 07:44
I've removed this issue form the product backlog and the unified projects as it was a duplicate of https://github.com/ARMmbed/mbedtls-test/issues/165 in those boards. I've kept it in the EPICs board as https://github.com/ARMmbed/mbedtls-test/issues/165 cannot be added to this project.

**Closed** 2021-09-14 08:42 UTC
Labels: enhancement, Product Backlog, size:S, component: test
