### ISSUE TITLE
Moving constants to rom section using gcc __attribute__

### ISSUE THREAD

**Issue by wilberforce** [ARMmbed/mbedtls#465] opened 2016-04-21 10:28 UTC
On the ESP8266, constants can be kept in iRom and not copied to valuable RAM:

https://github.com/ARMmbed/mbedtls/blob/development/library/sha256.c#L134

````
static const uint32_t K[] =
{
    0x428A2F98, 0x71374491, 0xB5C0FBCF, 0xE9B5DBA5,....
````

This can be achieved by:

#define IN_FLASH_MEMORY   __attribute__((section(".irom.literal"))) __attribute__((aligned(4)))
````
static const uint32_t K[] IN_FLASH_MEMORY  = { ...
````

For other achitecures, the #define IN_FLASH_MEMORY would be empty.

If I add this to a pull request, would you accept the request?

**Comment by jcowgill** [comment] 2016-04-21 10:48
Things like this should already be put in the `.rodata` section. Can you not map this section to flash memory in your linker script (I'm afraid I don't know much about the ESP8266 in particular though)?

**Comment by ciarmcom** [comment] 2016-04-21 19:51
ARM Internal Ref: IOTSSL-717

**Comment by wilberforce** [comment] 2016-04-21 21:02
Yes - you could map via a linker script. However - it's not that simple ;-)

Reads from flash must be on a 4 byte boundary as  a word. Consider:

````
static const unsigned char sha256_padding[64] = [ ... ]
```
This means that at to access this if it was in irom, it also needs to be read as words, as a read of sha256_padding[1] would cause an exception.

With the linker scrfipt, I don't believe you can be selective about which symbols go where...:

`static const uint32_t K[]` -> irom
`static const unsigned char sha256_padding[64]` -> rodata

**Comment by sbutcher-arm** [comment] 2016-04-21 23:07
Hi @wilberforce,

I think this is a duplicate of #406, raised by @pieceofsummer.

I can see the use in this and I've worked on platforms where this would be useful. We might consider a pull request, but we will probably want to adopt the same approach across other mbed components, so I'd hold off making the change just yet unless you want it for just yourself.

I'll close this issue and update #406. If you feel I've misunderstood something, please feel free to say so, and I'm happy to reopen the issue.

And thanks for the offer!

**Closed by sbutcher-arm** 2016-04-21 23:07 UTC
Labels: mirrored

**Comment by wilberforce** [comment] 2016-04-22 04:20
Thanks. #406 covers both code and const data.

Code (functions) can be done with linker scripts - so that all functions in SHA1.o  get moved to a irom.txt section.

The issue I have is _some_ of the rodata (containing most of the constants) can be moved to Irom without code changes - this is the data that is word sized and on word boundaries. The other data that byte sized can't, so linker scripts can't move the complete library.

**Comment by wilberforce** [comment] 2016-06-20 10:29
I found a work around without having to modify the source code.

By using a version of memcpy that reads eeprom on 32 byte boundaries, and moving rodata in the linking stage, the static data can be kept out of ram and moved to irom.

https://github.com/espruino/Espruino/pull/850/files
