### ISSUE TITLE
 undefined reference to `mbedtls_pk_parse_subpubkey'

### ISSUE THREAD

**Issue by DragonQuestHero** [ARMmbed/mbedtls#1069] opened 2017-08-30 11:30 UTC
I compiled the Release mbedtls-mbedtls-2.6.0 smoothly for ubuntu 16.04
(cmake .
make && make install)
but,when i ues mbedtls_ssl_get_peer_cert 
building error:
1>  Linking objects
1>  //usr/local/lib/libmbedx509.a(x509_crt.c.o): In function `x509_crt_parse_der_core':
1>  x509_crt.c:(.text+0x12c1): undefined reference to `mbedtls_pk_parse_subpubkey'
1>  //usr/local/lib/libmbedx509.a(x509_crt.c.o): In function `mbedtls_x509_crt_parse_file':
1>  x509_crt.c:(.text+0x18f3): undefined reference to `mbedtls_pk_load_file'
1>  collect2: error: ld returned 1 exit status
1>
1>//usr/local/lib/libmbedx509.a(x509_crt.c.o) : error :
1>x509_crt.c : error : undefined reference to `mbedtls_pk_parse_subpubkey'
1>//usr/local/lib/libmbedx509.a(x509_crt.c.o) : error :
1>x509_crt.c : error : undefined reference to `mbedtls_pk_load_file'
1>collect2 : error : ld returned 1 exit status
sorry my english
thanks

**Comment by RonEld** [comment] 2017-08-30 11:44
Hi @DragonQuestHero Thank you for reporting This!
We will look into this

**Comment by ciarmcom** [comment] 2017-08-30 11:50
ARM Internal Ref: IOTSSL-1695

**Comment by RonEld** [comment] 2017-08-30 12:34
Hi @DragonQuestHero Please note, that theoutput of the compilation is 3 libraries.
The functions that you are using ( e.g. `x509_crt_parse_der_core`) are defined in _`libmbedx509.a`_ and the mbedtls_pk_* functions that are used are defined in _`libmbedcrypto.a`_ :
~~~
nm library/libmbedcrypto.a | grep mbedtls_pk | grep " T "
0000000000000258 T mbedtls_pk_can_do
000000000000069e T mbedtls_pk_check_pair
000000000000078d T mbedtls_pk_debug
0000000000000592 T mbedtls_pk_decrypt
0000000000000618 T mbedtls_pk_encrypt
00000000000000a1 T mbedtls_pk_free
000000000000074d T mbedtls_pk_get_bitlen
00000000000007f4 T mbedtls_pk_get_name
0000000000000823 T mbedtls_pk_get_type
00000000000000ee T mbedtls_pk_info_from_type
0000000000000076 T mbedtls_pk_init
0000000000000138 T mbedtls_pk_setup
00000000000001a4 T mbedtls_pk_setup_rsa_alt
00000000000004f9 T mbedtls_pk_sign
00000000000002f0 T mbedtls_pk_verify
000000000000037f T mbedtls_pk_verify_ext
000000000000079d T mbedtls_pkcs12_derivation
0000000000000489 T mbedtls_pkcs12_pbe
0000000000000356 T mbedtls_pkcs12_pbe_sha1_rc4_128
00000000000001d7 T mbedtls_pkcs5_pbes2
000000000000062c T mbedtls_pkcs5_pbkdf2_hmac
0000000000000998 T mbedtls_pkcs5_self_test
000000000000006f T mbedtls_pk_load_file
0000000000001d57 T mbedtls_pk_parse_key
0000000000000200 T mbedtls_pk_parse_keyfile
0000000000002316 T mbedtls_pk_parse_public_key
00000000000002d8 T mbedtls_pk_parse_public_keyfile
0000000000000ed3 T mbedtls_pk_parse_subpubkey
0000000000000602 T mbedtls_pk_write_key_der
0000000000000cb4 T mbedtls_pk_write_key_pem
00000000000002ea T mbedtls_pk_write_pubkey
00000000000003bf T mbedtls_pk_write_pubkey_der
0000000000000bb6 T mbedtls_pk_write_pubkey_pem
~~~
You should verify that all three compiled Mbed TLS libraries are linked in your application

**Comment by DragonQuestHero** [comment] 2017-08-31 01:40
thank you guys
i used VS2015(Linux) in win10 remote bulid my project
[
![default](https://user-images.githubusercontent.com/21189903/29902220-4f30fc50-8e2f-11e7-8474-8c7108bde4f4.PNG)
the problem in here:mbedcrypto;mbedx509;
if i change libmbedcrypto and mbedx509 position
]
![default](https://user-images.githubusercontent.com/21189903/29902193-16da28c2-8e2f-11e7-8e33-37a9e62f1ab1.PNG)
mbedtls;mbedcrypto;mbedx509;(-l"mbedtls" -l"mbedx509" -l"mbedcrypto")
The problem is solved
but,i dont konw why= =....
1>  Linking objects
1>  X.vcxproj -> F:\Project\X\X\bin\x64\Release\X.out
========== 全部重新生成: 成功 1 个，失败 0 个，跳过 0 个 ==========
last:thank you again @RonEld  have a nice day

**Comment by RonEld** [comment] 2017-08-31 07:08
Hi @DragonQuestHero  I am happy you resolved your issue.
Dependent library order is known in toolchains, and you can find many posts on this scenario.
For example:
- [MSDN](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d69aeb0d-e5fb-41e1-98ad-9b6c7b43a3ca/problem-with-linking-dependent-static-libraries-in-vs-2010?forum=vcgeneral)
- [GCC](https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc)

Please close this issue, if no longer valid

**Closed** 2017-09-01 01:12 UTC
Labels: mirrored, question, tracking

**Comment by youjianchuqing** [comment] 2019-04-08 07:49
I 'm involved in the same problem,
Do you have found the new way to solve this problem without using VS2015,
Thanks!

**Comment by RonEld** [comment] 2019-04-08 08:00
@youjianchuqing Does my [comment](https://github.com/ARMmbed/mbedtls/issues/1069#issuecomment-326209833) regarding GCC addresses your problem?

**Comment by youjianchuqing** [comment] 2019-04-08 08:27
No, 
I use the command :
gcc -o mac  -lmbedtls -lmbedx509 -lmbedcrypto MAC.c  
but failed！

Environment：  Ubuntu18.04  or Ubuntu 16.04. And those dynamic libraries have been installed into the path '/usr/local/lib'

error log：
/tmp/ccQ7z3bW.o: In function `LoadMacKey':
CMAC.c:(.text+0x2a9): undefined reference to `mbedtls_aes_setkey_enc'
CMAC.c:(.text+0x309): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x37e): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x39d): undefined reference to `mbedtls_aes_setkey_enc'
CMAC.c:(.text+0x3e2): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x3fb): undefined reference to `mbedtls_aes_setkey_enc'
CMAC.c:(.text+0x46f): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x538): undefined reference to `mbedtls_aes_crypt_ecb'
/tmp/ccQ7z3bW.o: In function `VerifyMAC':
CMAC.c:(.text+0x5c1): undefined reference to `mbedtls_aes_setkey_enc'
CMAC.c:(.text+0x621): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x696): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x6b5): undefined reference to `mbedtls_aes_setkey_enc'
CMAC.c:(.text+0x6fa): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x713): undefined reference to `mbedtls_aes_setkey_enc'
CMAC.c:(.text+0x787): undefined reference to `mbedtls_aes_crypt_ecb'
CMAC.c:(.text+0x850): undefined reference to `mbedtls_aes_crypt_ecb'
collect2: error: ld returned 1 exit status

**Comment by youjianchuqing** [comment] 2019-04-08 08:46
I use the command:
      nm -D libmbedcrypto.so

The related functions have been complied into the  'libmbedcrypto.so' 

The result:
0000000000011d60 T mbedtls_aes_crypt_cbc
0000000000012080 T mbedtls_aes_crypt_cfb128
0000000000012180 T mbedtls_aes_crypt_cfb8
0000000000012300 T mbedtls_aes_crypt_ctr
0000000000011cf0 T mbedtls_aes_crypt_ecb
0000000000012250 T mbedtls_aes_crypt_ofb
0000000000011e60 T mbedtls_aes_crypt_xts
0000000000011ce0 T mbedtls_aes_decrypt
0000000000011870 T mbedtls_aes_encrypt
0000000000010d70 T mbedtls_aes_free
0000000000010d40 T mbedtls_aes_init
0000000000012f70 T mbedtls_aesni_crypt_ecb
0000000000012fd0 T mbedtls_aesni_gcm_mult
0000000000012f30 T mbedtls_aesni_has_support
0000000000013160 T mbedtls_aesni_inverse_key
00000000000131e0 T mbedtls_aesni_setkey_enc
00000000000123c0 T mbedtls_aes_self_test
0000000000011140 T mbedtls_aes_setkey_dec
0000000000010de0 T mbedtls_aes_setkey_enc

**Comment by RonEld** [comment] 2019-04-08 08:51
@youjianchuqing I am confused.
Are you using Mbed TLS as a shared object or as static libraries?
What is the Mbed TLS version you are using?

Have you tried 
~~~
gcc -o mac -lmbedtls -lmbedx509 -lmbedcrypto -lmbedtls -lmbedx509 -lmbedcrypto MAC.c
~~~
Sometimes, in GCC, there are some build dependencies between static libraries which causes such issues

**Comment by youjianchuqing** [comment] 2019-04-08 08:58
I have tried the shared objects and static libraries, but they all failed.
The used Mbed TLS version is mbedtls_2.16.1_apache

**Comment by DragonQuestHero** [comment] 2019-04-10 11:58
@youjianchuqing 国人么?
你需要调整依赖库的顺序 试试看
u need adjust .lib order

**Comment by youjianchuqing** [comment] 2019-04-10 16:07
@DragonQuestHero 
我犯了一个的错误:     gcc  MCA.c  -lmbedtls -lmbedx509 -lmbedcrypto  -o a
源文件（MAC.c）应该放置在 gcc 之后，而不是   gcc  -o a  -lmbedtls -lmbedx509 -lmbedcrypto  MCA.c
谢谢！


@RonEld 
 H!, 
     The root cause has been find. I make a foolish mistake, the order of command is  reversed. 
error：gcc  -o a  -lmbedtls -lmbedx509 -lmbedcrypto  MCA.c
right  : gcc  MCA.c  -lmbedtls -lmbedx509 -lmbedcrypto  -o a 

 Thanks!

**Comment by RodrigoDornelles** [comment] 2023-03-10 11:15
> @DragonQuestHero 我犯了一个的错误: gcc MCA.c -lmbedtls -lmbedx509 -lmbedcrypto -o a 源文件（MAC.c）应该放置在 gcc 之后，而不是 gcc -o a -lmbedtls -lmbedx509 -lmbedcrypto MCA.c 谢谢！
> 
> @RonEld H!, The root cause has been find. I make a foolish mistake, the order of command is reversed. error：gcc -o a -lmbedtls -lmbedx509 -lmbedcrypto MCA.c right : gcc MCA.c -lmbedtls -lmbedx509 -lmbedcrypto -o a
> 
> Thanks!

this solved for me, using sources before libraries.
