### ISSUE TITLE
About use known public key and signature to verify ECDSA

### ISSUE THREAD

**Issue by r06631041** [ARMmbed/mbedtls#4580] opened 2021-05-28 03:46 UTC
---------------------------------------------------------------
### Description
- Type: Feature Request
- Priority: Major 

---------------------------------------------------------------

**OS**  
Mbed OS|linux|

Hi all,
I want to confirm whether my code like this is correct.

Description:
I will get the public key and signature from others. So I try to find a way to feed the key and signature to the mbedtls program.
as the below is my code, when it's compiled in visual studio ret==0, but when it ran on the arm architecture platform ret==0xffffb300. 

In response to this, I would like to ask for your help here. Thanks.

        mbedtls_ecdsa_context  ctx_verify;
        int ret = 0;
		
        mbedtls_ecdsa_init(&ctx_verify);
        mbedtls_ecp_curve_info* curve_info = mbedtls_ecp_curve_info_from_grp_id(MBEDTLS_ECP_DP_SECP256R1);
        ret = mbedtls_ecp_group_load(&ctx_verify.grp, curve_info->grp_id);

        unsigned char public_key[65] = { 0 };
        unsigned char public_key_string[] = "04C2E29392617F1CCA8ABE8E3415A4E452BAA274DA100A4709466A22F8E6A8B1E3E73BC00C2DDFACD19ECAC0DEE2202A1971ED14AE83A577D649570DEE4CAE8DE4";
        unsigned char hash[32] = { 0 };
        unsigned char hash_string[] = "02F4CCF09D1F5740E28864C430F866B46B697646D376E7813D12B873DBE16CC6";
	unsigned char sig[71] = { 0 };
        unsigned char sig_string[] = "3045022100A5CDE0DD9E025FD9CF1A02E1587F1154C1FF4D3BE25968548F4519572AC583D00220175617F1F8A6A16ECE5F5D4AFC12E10931B4BCC666BAA5A9840B4775B6B31A25";
		
		// "04CE29..." will be converted to {0x04,0xCE,0x29...} and save in public_key buffer
		TranslateACSIItoByte(public_key_string, public_key, 65);  
        TranslateACSIItoByte(hash_string, hash, 32);
        TranslateACSIItoByte(sig_string, sig, 71);
 
        ret = mbedtls_ecp_point_read_binary(&(&ctx_verify)->grp, &(&ctx_verify)->Q, public_key, 65);

        printf("\nret=%d\n", ret);
        dump_pubkey("  + Public key: ", &ctx_verify);

        mbedtls_printf(" ok\n  . Verifying signature...");
        ret = mbedtls_ecdsa_read_signature(&ctx_verify, hash, sizeof(hash), sig, 71);
        printf("\nret=%d\n", ret);

**Comment by gilles-peskine-arm** [comment] 2021-05-28 10:32
Error codes from `mbedtls_xxx` functions are negative values. `ret` is actually -19712. You can use `programs/util/strerror` to print the corresponding error message:
```
Last error was: -0x4d00 - ECP - Generation of random value, such as ephemeral key, failed
```
There's probably something wrong with the integration of the RNG in your application.

**Comment by gilles-peskine-arm** [comment] 2021-05-28 10:33
I am closing this issue because it is a support request, not a bug report or a feature request. In the future, for support requests, please post on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls).

**Closed by gilles-peskine-arm** 2021-05-28 10:33 UTC
