### ISSUE TITLE
Use of uninitialized value in `mbedtls_mutex_init()`.

### ISSUE THREAD

**Issue by sznaider** [ARMmbed/mbedtls#843] opened 2017-03-10 09:18 UTC
Hello, during development of an application that uses mbed TLS (version 2.4) as a DTLS backend, I found an interesting and random behavior. The library sometimes hang in `mbedtls_ssl_handshake()` even though I was using it correctly according to examples located in the mbed TLS source directory.

Then, a friend of mine tested my code on his station, and everything worked for him, which already was alarming. His version of mbed TLS was 2.2. Also, with mbed TLS 2.3 my code worked fine as well.

OK, so eventually I compiled version 2.4 with debug flags, with **threading** enabled:
- `#define MBEDTLS_THREADING_C 1`
-  `#define MBEDTLS_THREADING_PTHREAD 1`

were both set in `include/mbedtls/config.h`.

Then I ran it under valgrind which shown uses of uninitialized values in `threading_mutex_init_pthread()`. 

After a while we have found that #631 introduced a seemingly innocent change... Checking if mutex is valid before doing re-initialization, to make sure no one does it by accident as that would invoke an undefined behavior.

Now, I was not able to find any information about the need of memsetting the mutex before calling `mbedtls_mutex_init()` (which would be weird anyway, because after all its purpose is to initialize, right?).

Some `*_init()` functions (e.g. `mbedtls_ssl_cookie_init()`) in the mbed TLS codebase that has this, or equivalent piece of code:

```c
#if defined(MBEDTLS_THREADING_C)
    mbedtls_mutex_init( &ctx->mutex );
#endif

```

makes use of uninitialized values, because none of it seem to zeroize the mutex first.

**Comment by sbutcher-arm** [comment] 2017-03-11 08:58
Thanks for raising this! Looks a bit worrying that we didn't catch this in our testing. We'll look into it.

**Comment by ciarmcom** [comment] 2017-03-13 20:51
ARM Internal Ref: IOTSSL-1254

**Comment by sbutcher-arm** [comment] 2017-05-13 21:36
As has been already observed, this is a duplicate of issue #667, so am closing it as a duplicate issue.

**Closed by sbutcher-arm** 2017-05-13 21:36 UTC
Labels: bug, mirrored, tracking
