### ISSUE TITLE
Bignum.c in mbedTLS 2.16.1 and later not working

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#2968] opened 2019-12-22 09:04 UTC
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug 
- Priority: Major 

---------------------------------------------------------------
## Bug

copied from the [forum](https://forums.mbed.com/t/bignum-c-in-mbedtls-2-16-1-and-later-not-working/6449), by Mike Taylor

We had mbedTLS 2.5.2 working well on our embedded hardware which utilizes the Analog Devices Blackfin 51x family of CPUs, which operates little-endan. When we upgraded to 2.16.3 our embedded HTTPS server did not work anymore. It just reset the connection not too far into the TLS negotiations with browsers.

Upon investigating I found that bignum.c is to blame. The version of bignum.c in mbedTLS 2.16.0 works and I can use it in 2.16.2 or 2.16.3 with good results. But the versions of bignum.c in any of mbedTLS 2.16.1, 2, or 3 do not work well.

I think the root problem is likely related to the endian conversions in the later versions but it isn’t quite clear. I know that for many years our software uses a macro for the endian conversion and on a little-endian system it is

#define Ntohl(val) 
( (((u32)(val) >> 24) & 0x000000FF) | 
(((u32)(val) >> 8) & 0x0000FF00) | 
(((u32)(val) << 8) & 0x00FF0000) | 
(((u32)(val) << 24) & 0xFF000000) )

This appears to be quite different from the mpi_uint_bigendian_to_host_c() function in 2.16.3 but
I can’t spend more time on it. I’ve already spent quite a lot tracking down the problem.

We build the code with Visual DSP 5.1.2 with build date May 30 2013. It is worth noting that it
does NOT define BYTE_ORDER so mpi_uint_bigendian_to_host_c() is used.

**Comment by yanesca** [comment] 2020-01-23 11:45
Could you please provide some more information on how to reproduce this bug?

**Comment by RonEld** [comment] 2020-01-23 12:01
This is all that was stated in the forum post

**Comment by gilles-peskine-arm** [comment] 2020-02-12 12:14
I'm sorry, but there is simply not enough information to determine what the problem is, or even if there is any problem in Mbed TLS itself rather than in the code using it. We don't know what functions are involved, with what parameters they are called, or why endianness would be an issue (the bignum code only cares about endianness when it's importing or exporting data, it doesn't care about the endianness of the platform).

I'm closing this issue. Please reopen it if you have a way to reproduce the problem. At least which function(s) are being called and with which parameters, preferably with a small program that works with Mbed TLS version X and fails with Mbed TLS version Y.

**Closed by gilles-peskine-arm** 2020-02-12 12:14 UTC
Labels: bug, component: Crypto

**Comment by RonEld** [comment] 2020-02-12 13:41
Everything is written in the post:
Mbed TLS version: 2.16.1 and later fails. But, in Mbed TLS 2.16.0 it succeeds.
So, the changes caused to `bignum.c` caused the failure.
As mentioned:
> I think the root problem is likely related to the endian conversions in the later versions but it isn’t quite clear. I know that for many years our software uses a macro for the endian conversion and on a little-endian system it is
