### ISSUE TITLE
Question:  Using mbedTLS_cert_verify() without `setting is_ca=1` for a self-signed CA

### ISSUE THREAD

**Issue by Darsh-Dev** [ARMmbed/mbedtls#5379] opened 2022-01-03 11:13 UTC
### Summary

I have a certificate chain containing a device certificate and a self-signed CA certificate. I'm trying to verify the device certificate against this CA. for verification I'm using  `mbedtls_x509_crt_verify` API.
While verifying I am getting the error with self-signed CA.

### System information

Mbed TLS version (number or commit id): 2.16.9
Operating system and version: FreeRTOS
Configuration (if not default, please attach `mbedtls_config.h`): Default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): ESP-IDF
Additional environment information: 

### Expected behavior
Certification should pass/verify with Self-signed CA.

### Actual behavior
I'm getting the below error while verifying the device certificate against the Self-Signed CA.
![image](https://user-images.githubusercontent.com/52735713/147923895-0916a4ac-4735-47b7-9f08-b6631191d708.png)

### Steps to reproduce and Additional information

If I verify the same certificate using **OpenSSL** command IT works.

> openssl verify -verbose -show_chain -CAfile test_cacrt.pem test_crt.pem 
test_crt.pem: OK
Chain:
Depth=0:
Depth=1:

As stated [here](https://tls.mbed.org/kb/how-to/generate-a-self-signed-certificate).
![image](https://user-images.githubusercontent.com/52735713/147924087-1ac60f72-89f8-41b2-9c49-6115f50bc5ea.png)

So, I set is_ca = 1 manually in the firmware and then tried performing verification again and in that case the verification was successful.  

The issue is I'm not sure if this is a valid solution. As stated in [mbedTLS API document](https://tls.mbed.org/api/group__x509__module.html#ga98ed4504e4f832b735a230acf54fcde3). If we look at the `mbedtls_x509_crt_verify` API there is a **NOTE** which states self-signed end-entity certificates to be trusted (for specific peers you know) - in that case, the self-signed certificate doesn't need to have the CA bit set.
![image](https://user-images.githubusercontent.com/52735713/147924285-6b20a3ff-94cd-4b76-8614-49a9dbff2e95.png)

**Comment by minosgalanakis** [comment] 2022-01-04 15:36
I was wondering weather this is more of question rather than an an issue. I agree that the wording could be more clear.

As I understand it, since that self signed certificate is expected to sign others, is should have that bit set. Looking at the tests directory we are also setting this bit:

~~~~~
tests/data_files/Makefile:      $(MBEDTLS_CERT_WRITE) is_ca=1 
~~~~~

So I would wager that is the expected behaviour. As to the context of the note section, I hope some more experienced community member could provide some more clarity.

**Comment by gilles-peskine-arm** [comment] 2022-01-04 17:05
A self-signed certificate doesn't have to have is_ca=1 if you use it without a CA. But a CA always has to have is_ca=1. It doesn't matter whether the CA certificate is self-signed (common case) or signed by another CA (also possible).

In your scenario with a CA certificate and a device certificate:
* The CA certificate should be self-signed and must have is_ca=1.
* Only the CA should know the private key for the CA certificate.
* The device certificate must be signed by the CA certificate and must have is_ca=0.
* The device needs to know the private key for the device certificate.
* On the server, you must declare the CA certificate as trusted.
* The server does not need to have any prior knowledge of the device certificate.

I don't know exactly what you did with openssl (you didn't post the commands you used to generate the certificate), but I'm sure that it does not accept a certificate that is signed by another certificate if that other certificate doesn't have is_ca=1.

**Comment by gilles-peskine-arm** [comment] 2022-01-04 17:06
> If we look at the mbedtls_x509_crt_verify API there is a NOTE which states self-signed end-entity certificates to be trusted (for specific peers you know) - in that case, the self-signed certificate doesn't need to have the CA bit set.

This is correct. But since you're using a CA, it doesn't apply to you.

**Comment by gilles-peskine-arm** [comment] 2022-01-04 17:06
I'm closing this issue because it's a support request, not a feature request or a bug report.

**Closed by gilles-peskine-arm** 2022-01-04 17:06 UTC
Labels: question, Community
