### ISSUE TITLE
How to inject salt value in verifying RSA PSS

### ISSUE THREAD

**Issue by r06631041** [ARMmbed/mbedtls#3972] opened 2020-12-23 11:19 UTC
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Feature Request
- Priority:  Minor

---------------------------------------------------------------

## Question
I'm trying to run the CAVP test vector for PKCS#1 RSASSA PSS signature verification.
Here's an example:
> n = be499b5e7f06c83fa0293e31465c8eb6b58af920bae52a7b5b9bfeb7aa72db1264112eb3fd431d31a2a7e50941566929494a0e891ed5613918b4b51b0d1fb97783b26acf7d0f384cfb35f4d2824f5dd380623a26bf180b63961c619dcdb20cae406f22f6e276c80a37259490cfeb72c1a71a84f1846d330877ba3e3101ec9c7b

> p = e7a80c5d211c06acb900939495f26d365fc2b4825b75e356f89003eaa5931e6be5c3f7e6a633ad59db6289d06c354c235e739a1e3f3d39fb40d1ffb9cb44288f
> q = d248aa248000f720258742da67b711940c8f76e1ecd52b67a6ffe1e49354d66ff84fa601804743f5838da2ed4693a5a28658d6528cc1803bf6c8dc73c5230b55
> SHAAlg = SHA512
> e = 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011
> d = 0d0f17362bdad181db4e1fe03e8de1a3208989914e14bf269558826bfa20faf4b68dba6bb989a01f03a21c44665dc5f648cb5b59b954eb1077a80263bd22cdfb88d39164b7404f4f1106ee01cf60b77695748d8fdaf9fd428963fe75144010b1934c8e26a88239672cf49b3422a07c4d834ba208d570fe408e7095c90547e68d
> Msg = c7f5270fca725f9bd19f519a8d7cca3cc5c079024029f3bae510f9b02140fe238908e4f6c18f07a89c687c8684669b1f1db2baf9251a3c829faccb493084e16ec9e28d58868074a5d6221667dd6e528d16fe2c9f3db4cfaf6c4dce8c8439af38ceaaaa9ce2ecae7bc8f4a5a55e3bf96df9cd575c4f9cb327951b8cdfe4087168
> S = 8ffc38f9b820ef6b080fd2ec7de5626c658d79056f3edf610a295b7b0546f73e01ffdf4d0070ebf79c33fd86c2d608be9438b3d420d09535b97cd3d846ecaf8f6551cdf93197e9f8fb048044473ab41a801e9f7fc983c62b324361dade9f71a65952bd35c59faaa4d6ff462f68a6c4ec0b428aa47336f2178aeb276136563b7d
> SaltVal = 11223344555432167890
> Result = P

so I use  `mbedtls_rsa_rsassa_pss_verify` to implement. However, I don't know how to inject salt value,whether there are any functions that can be used, or examples.
By the way, I use `mbedtls_rsa_import_raw` to import the public key.

Thanks!

**Comment by mpg** [comment] 2020-12-23 16:44
Hi @r06631041! I think someone recently had the same problem so we already have an open issue about it: #3152 - as you can read there, if the salt has the expected size, you can use `f_rng`, `p_rng` to inject the value you want; for other lengths of the salt this is currently not possible, but there is an open PR extending the API to support that: #3183.

I'm closing this as a duplicate of #3152 - feel free to continue the discussion there if needed.

**Closed by mpg** 2020-12-23 16:44 UTC
