### ISSUE TITLE
Compilation error in mbedTLS 2.3.0

### ISSUE THREAD

**Issue by Marian-Kechlibar** [ARMmbed/mbedtls#549] opened 2016-07-22 11:37 UTC
I was testing mbedTLS 2.3.0 compilation from source. As long as "MBEDTLS_TIMING_C", "MBEDTLS_HAVE_TIME", "MBEDTLS_HAVE_TIME_DATE" are all unset, the code compiles. It does not verify certificate expirations, of course.

When I set "MBEDTLS_HAVE_TIME", "MBEDTLS_HAVE_TIME_DATE", but "MBEDTLS_TIMING_C" remains unset, the code no longer compiles and complains about undefined **time_t** in _ssl.h_. 

I patched the problem by adding a **#include "platform.h"** to the beginning of the _ssl.h_ header. Should I create a pull request for that patch?

The problem is unlikely to affect many users.

**Comment by sbutcher-arm** [comment] 2016-07-22 12:00
Hi,

I think this issue is a duplicate of #522 and has now been fixed in the development head. Please checkout the development branch and see if you still have a problem.

As such I'm closing the bug, but if the fix doesn't work for you or you have any other problems, please feel free to reply or open the bug.

**Closed by sbutcher-arm** 2016-07-22 12:00 UTC
Labels: bug
