### ISSUE TITLE
mbedTLS accepts a certificate which has duplicate certificate policy IDs without any warning

### ISSUE THREAD

**Issue by chenchuAtXidian** [ARMmbed/mbedtls#804] opened 2017-02-14 01:29 UTC
Summary: As for a certificate, its certificate policy IDs should not be duplicate. However, mbedTLS accepts such a certificate  without any warning.
   
   Versions of mbedTLS: 2.3.0
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  mbedtls_cert_app mode='file' filename=43.pem ca_file=ca.pem
   
   Actual results: OK
   Expected results: mbedTLS should reject such a certificate or give some warnings at least.
   
   The attachement contains ca.pem and 43.pem.
   
   Please rename the file "test cases.txt" to "test cases.zip" and extract it.

[test cases.txt](https://github.com/ARMmbed/mbedtls/files/772881/test.cases.txt)

**Comment by RonEld** [comment] 2017-02-15 08:58
Thank you for reporting this issue

**Comment by ciarmcom** [comment] 2017-02-15 12:50
ARM Internal Ref: IOTSSL-1221

**Comment by NWilson** [comment] 2017-02-15 22:24
This is a drop in the bucket - given that most TLS libraries completely ignore X.509 policies, I'd have thought that behaviour was more important!

X.509 policies are very little-used. Are there any policies that you'd actually want mbedTLS to implement? As it stands, adding a check for policy IDs (but then ignoring the policy itself) would seem rather strange.

**Comment by mpg** [comment] 2018-03-19 12:44
Thanks for your report! RFC 5280 indeed says that:
```
    A certificate policy OID MUST NOT appear more than once in a
   certificate policies extension.
```
However we think this requirement should apply to issuing CAs rather than validating parties: as a general rule, if a trusted CA signed a certificate, we don't see a need to enforce standards compliance more strictly than the trusted CA did (beyond what is necessary to make sure we can process and verify the certificate in a secure way).

In addition, considering that, as @NWilson mentioned, we currently don't support the Certificate Policies extension at all, and that the RFC explicitly allows implementation to completely ignore extensions they don't support (unless they're marked critical obviously) we really don't think we have any standards requirement to enforce this, nor that it would bring any value to our users.

Therefore closing as "not a bug". If you disagree, please re-open explaining why, based on quotes from standards.

**Closed by mpg** 2018-03-19 12:44 UTC
Labels: bug, mirrored, tracking
