### ISSUE TITLE
mbedTLS compiled with clang incorrectly rejects certificates (broken validation)

### ISSUE THREAD

**Issue by sfan5** [ARMmbed/mbedtls#4917] opened 2021-09-04 15:29 UTC
### Summary

mbedTLS will reject certificates that are valid, instead returning `MBEDTLS_ERR_X509_CERT_VERIFY_FAILED`.
This only happens if mbedTLS is built with Clang and only since 0.27.0.

### System information

Mbed TLS version: `0.27.0`
Operating system and version: Linux glibc
Configuration: default
Compiler and options: `clang version 12.0.1`

### Steps to reproduce

This can be reproduced with the `ssl_server` and `ssl_client1` test programs, which the following script does:

```bash
rm -rf mbedtls-2.27.0
wget 'https://github.com/ARMmbed/mbedtls/archive/refs/tags/v2.27.0.tar.gz' -O - | tar -xz
cd mbedtls-2.27.0
make -j4 programs

./programs/ssl/ssl_server &>/dev/null &
sleep 1
./programs/ssl/ssl_client1
killall ssl_server
```

### Expected behavior

When ran with `CC=gcc` or if the script is edited to build 0.26.0 or earlier
<pre>
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake... ok
  . Verifying peer X.509 certificate... ok
  &gt; Write to server: 18 bytes written

GET / HTTP/1.0

  &lt; Read from server: 156 bytes read

HTTP/1.0 200 OK
Content-Type: text/html

&lt;h2&gt;mbed TLS Test Server&lt;/h2&gt;
&lt;p&gt;Successful connection using: TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256&lt;/p&gt;
ssl_msg.c:4090: mbedtls_ssl_handle_message_type() returned -30848 (-0x7880)
ssl_msg.c:5543: mbedtls_ssl_read_record() returned -30848 (-0x7880)
</pre>

### Actual behavior

When ran with `CC=clang`:
<pre>
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...ssl_tls.c:2620: x509_verify_cert() returned -9984 (-0x2700)
ssl_msg.c:4714: mbedtls_ssl_fetch_input() returned -29312 (-0x7280)
ssl_msg.c:4065: ssl_get_next_record() returned -29312 (-0x7280)
ssl_cli.c:3101: mbedtls_ssl_read_record() returned -29312 (-0x7280)
 failed
  ! mbedtls_ssl_handshake returned -0x7280

Last error was: -29312 - SSL - The connection indicated an EOF
</pre>

**Comment by gilles-peskine-arm** [comment] 2021-09-06 10:46
We've had a previous report of a bug with Clang 12: https://github.com/ARMmbed/mbedtls/issues/4786 . We think that it's due to a Clang bug but we haven't completed the investigation so it's still possible that the problem is undefined behavior in Mbed TLS. Do the unit tests pass for you? Can you try with an older Clang version or with reduced optimization?

**Comment by sfan5** [comment] 2021-09-06 13:55
The test suite shows a failure for `test_suite_dhm`, at `test_suite_mpi` it hangs indefinitely.

Other options tested using ssl_server + ssl_client1 like before:

Compiler | `-O1` | `-O2` (default)
-------- | ----- | ---------------
clang 12.0.1 | :heavy_check_mark:  | :x: 
clang 11.0.0 | :heavy_check_mark: | :heavy_check_mark:

I'm inclined to say this is indeed a duplicate of the bug you linked.

**Comment by davidhorstmann-arm** [comment] 2021-09-06 14:32
I have reproduced these results on the latest `development_2.x` and with clang-13. As with #4786, annotating `mpi_mul_hlp` with `noinline` fixes the issue, so it seems likely to be the same.

**Comment by gilles-peskine-arm** [comment] 2021-09-06 15:30
Closing as a duplicate of https://github.com/ARMmbed/mbedtls/issues/4786

**Closed by gilles-peskine-arm** 2021-09-06 15:30 UTC
Labels: bug, regression
