### ISSUE TITLE
all.sh does not include all available tests on a full configuration

### ISSUE THREAD

**Issue by simonbutcher** [ARMmbed/mbedtls#2002] opened 2018-09-03 07:31 UTC
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**Expected behavior**   

`all.sh` is the project 'release test script' and supposedly includes all tests that can be included on a single platform. It doesn't execute Windows tests, nor on-target tests that could be executed on an embedded platform, but it does include all tests that could be included on a Linux/POSIX platform.

**Actual behavior**  

The code coverage script, `basic-build-test.sh` runs all tests - the test suites, `ssl-opt.sh` and `compat.sh` - on a configuration that includes all options enabled. So all tests with an 'all options enabled' build.

Issue #2001 has shown that `all.sh` does does not include this test as `all.sh` is passing yet `basic-build-test.sh` is failing.

**Comment by ciarmcom** [comment] 2018-09-03 07:54
ARM Internal Ref: IOTSSL-2494

**Comment by gilles-peskine-arm** [comment] 2020-04-09 16:18
I'm not sure when this was fixed, but we do now run all of `ssl-opt.sh` and `compat.sh` in the `full` config in `all.sh` (`component_test_full_cmake_gcc_asan`).

However this is still not enough to ensure that if `all.sh` passes then `basic-build-test.sh` passes. There are seemingly minor environment differences that can matter.

* Different compiler options (which I've never seen to matter, but it could).
* Different way to create `seedfile`, which I have seen to cause a failure (during the 2.22 relase).
* Potentially different versions of OpenSSL and GnuTLS, which I have seen to cause a failure (during the 2.22 release).

We should run `basic-build-test.sh` as an `all.sh` job!

**Comment by mpg** [comment] 2020-04-10 07:40
> We should run basic-build-test.sh as an all.sh job!

Or just add `basic-build-test.sh` to the CI PR job, with the same environment as in the release job (in case `all.sh` might provide environment that running on its own doesn't, like creating a suitable seedfile.) Or at the very least in the nightly job. Either way, I'm surprised we still don't run `basic-build-test.sh` until the preparation of the release, I thought we had learned from previous incidents. Apparently we're a bit slow on that one.

**Comment by mpg** [comment] 2020-04-10 07:46
Oh well I just checked and we do run `basic-builld-test.sh` nighlty (that's how the nightly reports get coverage data). So perhaps the problem is "just" that this script failed to report failures properly.

After thinking about it for 5 minutes more than in my previous message, I'm now wondering if perhaps it'd better to leave `basic-build-test.sh` in the nightly job and out of the PR job, as it takes a pretty long time to run, the PR job is already slow enough as it is.

**Comment by gilles-peskine-arm** [comment] 2020-04-10 08:04
>  as it takes a pretty long time to run

It takes about 40 minutes. The slowest components of `all.sh` take a little over 20 minutes. They're executed in parallel, but there are fewer executors than components, and a run takes about 50 minutes when the CI is a lightly loaded.

We could save some time by not running interop tests, only `compat.sh -p mbedTLS` and `ssl-opt.sh` and we could even run those two in parallel. Interop testing should not contribute to the test coverage after all. I'll play with this for after the upcoming release.

**Comment by mpg** [comment] 2020-04-10 08:43
> not running interop tests

I'm curious to see if it changes coverage (other implementations might be doing things that we don't for example until one year ago they could pack multiple DTLS records into a single datagram and we couldn't). Even then, if that turns out to be the case, we could add tests to `ssl-opt.sh` (and document what code paths they're meant to exercise, which would be better than the current situation where I really don't know whether there are such code paths at all).

> run those two in parallel

**Comment by redtangent** [comment] 2020-04-10 11:05
`basic-build-test.sh` is a script to measure the test coverage when you execute all the basic test scripts. It's supposed to be a way to quantify the tests and how good they are. It's not necessarily the best means to execute the tests itself, and exists to deliver code coverage figures for those who want such figures.

So it's probably best as a nightly CI job, and `all.sh` should duplicate the missing tests _without measuring test coverage_ so it can do it optimally.

Else I think you risk conflating the purpose of these two separate scripts.

**Comment by gilles-peskine-arm** [comment] 2020-04-10 11:36
Why would we want to not measure the test coverage in each PR?

(Other than the workload, which I think today is acceptable.)

**Comment by redtangent** [comment] 2020-04-10 12:06
Well, you could do, and if you did there's my PR #2043, which set test thresholds for coverage, so if a PR causes the test coverage to fall below a certain threshold it would cause the PR to be rejected by the CI.

But this isn't something that is done today, and my point was that `all.sh` should be doing a comprehensive test pass, not slowed down by gathering test coverage data.

If you want to measure test coverage, make it a separate CI job calling out to `basic-build-test.sh`.

**Comment by gilles-peskine-arm** [comment] 2020-04-10 12:26
It looks like you're opposing measuring test coverage over all of `all.sh`. But nobody proposed this! My proposal is to run `basic-build-test.sh` from `all.sh`. I think we can do it without making the CI significantly slower.

**Comment by redtangent** [comment] 2020-04-10 12:49
The point I came in on, was that `basic-build-test.sh` and `all.sh` have different functions.

The whole test system is a bit messy, with no clean separation of date, test code, and configuration, nor it seems what should be a configuration of the CI versus what should be a test script, with the boundary blurred.

As `all.sh` has grown it has slowly moved from being a test script to a means to configure the CI. 

I think putting `basic-build-test.sh` into `all.sh` further clouds these boundaries.

If the problem - as stated at the top - is that `all.sh` doesn't have the same code coverage as `basic-build-test.sh`, then add those tests to `all.sh` without the coverage.

If the problem is the per-PR CI job needs code coverage figures, then that is a different issue and not stated in the problem above, but the solution should be run `basic-build-test.sh` as an extra CI job.

If the problem is both - then why do you need to add `basic-build-test.sh` to `all.sh`? What is `all.sh`'s and `basic-build-test.sh`'s purpose? Is it to be CI scripts? Or is it to be test scripts any developer can use? The answer seems to be what the team wants it to be at the time.

I'm not against adding `basic-build-test.sh` to `all.sh` in principle, but given there's a lack of design for how the scripts are used, I think it should be thought through, and be part of a wider approach. Not just what is needed today.

**Comment by gilles-peskine-arm** [comment] 2020-04-10 13:04
Ideally, I'd like `all.sh` to contain all the testing that we want to declare a version as acceptable, and a CI run would consist of running `all.sh` on each of the supported host platforms. The development branch should be releasable at any time, so acceptability for merging into development and acceptably for releasing are the same thing.

We've gotten there for the testing performed on Linux apart from coverage measurement.

The test scripts should work in any reasonable environment. The job of the CI is to trigger the test scripts and collect results. The difference between “test scripts any developer can use” and “CI scripts” is not what they do, it's the level of organization.

The difference between “ideally” and practice is due to the lack of human resources to make it so, and the lack of computing resources to keep PR feedback acceptably fast.

**Comment by gilles-peskine-arm** [comment] 2020-04-10 17:59
Coverage results for the upcoming 2.22, with SSL3 added back in:
```
Lines Tested       : 23713 of 27742 85.4%
Functions Tested   : 1588 of 1656 95.8%
```

Coverage results without interoperability, i.e. only unit tests, `ssl-opt.sh` and `compat.sh -p mbedTLS -e ''` (which includes a few failures because this includes null and RC4 ciphersuites but those are disabled in the build):
```
Lines Tested       : 23669 of 27734 85.3%
Functions Tested   : 1587 of 1656 95.8%
```

Coverage results without `compat.sh` at all, just unit tests and `ssl-opt.sh`:
```
Lines Tested       : 23595 of 27734 85.0%
Functions Tested   : 1585 of 1656 95.7%
```

I timed the various parts and the current runs of `compat.sh` take about 4× the time `ssl-opt.sh` takes, whereas .

**Comment by mpg** [comment] 2020-04-14 07:31
Thanks running those experiments and sharing the results!

I have trouble making sense of the difference between the 2nd and 3rd results: it looks like when you enable RC4 in the build, it results in 6 less lines being reached (out of the same total number of executable lines)? Could it possibly be a typo?

Now I'm wondering if there's a convenient way to diff coverage results, because I'm curious to know what 3 functions (and code lines) are exercised by `compat.sh` but not `ssl-opt.sh`, and same for the lines exercised `compat.sh` with all peers but not just ourselves. I think regardless of what we do with `basic-build-test.sh` it would be good to improve our understanding of this. I'm also inclined to add a few tests to `ssl-opt.sh` to cover those cases as well - and document why the new tests are there, ie what exactly they exercise that's not already exercised by other tests in `ssl-opt.sh`.

**Comment by gilles-peskine-arm** [comment] 2020-04-19 20:22
The differences between no-rc4 and with-rc4 are all DTLS code related to retransmission or to reception of an unexpected packet, which shows not only that running `compat.sh` on RC4 didn't add coverage compared to `ssl-opt.sh`, but more worryingly that running [`ssl-opt.sh` cannot be relied upon to exercise everything we would like it to exercise depending on its random seed](https://github.com/ARMmbed/mbedtls/issues/3206).

The three functions not hit without `compat.sh` are `ssl_parse_server_ecdh_params` (but `ssl_parse_server_ecdh_params_psa` is hit), `ssl_parse_server_psk_hint` and `ssl_calc_verify_ssl`.

I used an ad hoc perl script to transform the HTML to remove dates and hit counts. I hadn't saved the trace files (which `basic-build-test.sh` removes), otherwise `lcov --diff` would have come in handy.

**Comment by gilles-peskine-arm** [comment] 2021-12-16 10:28
I'm closing this issue because I've filed more specific issues for the two gaps that exist in our current CI: https://github.com/ARMmbed/mbedtls-test/issues/25 and https://github.com/ARMmbed/mbedtls-test/issues/27.

**Closed by gilles-peskine-arm** 2021-12-16 10:28 UTC
Labels: bug, mirrored, tracking, component: TLS
