### ISSUE TITLE
Handshake process takes very long, watchdog needs kicking during the handshake

### ISSUE THREAD

**Issue by umanayana** [ARMmbed/mbedtls#1884] opened 2018-07-25 18:24 UTC
Hello, 

I am running into a problem where the `mbedtls_ssl_handshake()` is taking so long that my watchdog is resetting the system. The handshake process is taking around 7 to 10 seconds. I am connecting to AWS IoT Core server.
Just to clarify the handshake process is successful this was test when I disable the watchdog.

What is the best way for me to kick my watchdog while the handshake process is occurring? 
The only method I can see which might work is kicking my watchdog during the send and receive callbacks that I set when i call `mbedtls_ssl_set_bio()`.

The other option is to change my watchdog time, but I don't like this approach as it could lead to future problems. I prefer to keep my watchdog timing strict.

**Comment by RonEld** [comment] 2018-07-26 07:30
@umanayana Have you managed to narrow down what is the bottle neck of your operation?
I doubt the issue is related to the send and receive callback. I believe the issue is in your certificate veriofication and \ or key exchange. From another [post](https://github.com/ARMmbed/mbedtls/issues/1858) I understand that you are using ECC operations. Note these operations are time consuming. Since you have your alternative implementation for ECDSA, I suggest you consider kicking your watchdog in your alternative implementations.

>The other option is to change my watchdog time, but I don't like this approach as it could lead to future problems. I prefer to keep my watchdog timing strict.

I agree, this is not recommended.

**Comment by umanayana** [comment] 2018-07-26 12:14
Hi Ron, 

The bottle neck is due to the signing, I haven't yet added the hardware accelerator I was just surprised that it's taking this long.
Once I had the hardware accelerator, I am hoping the time drops significantly.

**Comment by RonEld** [comment] 2018-07-26 12:35
Thank you for your confirmation.
This is what I thought. ECC operation consume time, and I believe that once you have Hardware acceleration for it, you won't encounter the watchdog

**Comment by RonEld** [comment] 2018-07-26 12:37
Closing as I believe the question was addressed. If after you enable hardware acceleration for ECDSA you still get watchdog triggered, please reopen.

**Closed by RonEld** 2018-07-26 12:37 UTC
Labels: question
