### ISSUE TITLE
"RSA-The PKCS#1 verification failed" on XCode13.1

### ISSUE THREAD

**Issue by codeservice** [ARMmbed/mbedtls#5152] opened 2021-11-10 15:27 UTC
### Summary

I recompiled old project on XCode13.1 and now have error for mbedtls_ssl_handshake (with MBEDTLS_SSL_VERIFY_NONE)
Error message: "RSA - The PKCS#1 verification failed"

I didn't have this issue with older XCode versions. No changes in my project files and compiler flags.
The same project compiled on windows works correctly.

### System information

Mbed TLS version (number or commit id): 2.26.0 and 2.27.0
Operating system and version: MacOS 11.6 / XCode13.1
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

mbedtls_ssl_handshake without verification should not fail on MacOS

### Actual behavior

Error message: "RSA - The PKCS#1 verification failed"

### Steps to reproduce

Compile MBED on XCode 13.1

**Comment by gilles-peskine-arm** [comment] 2021-11-15 20:28
This is probably #4116, which is fixed (at least for x86_64 and arm64) in the [`development`](https://github.com/ARMmbed/mbedtls/tree/development) (future 3.1) and [`development_2.x`](https://github.com/ARMmbed/mbedtls/tree/development_2.x) (future 2.28) branches. Please check if using the `development_2.x` branch fixes your problem.

**Comment by codeservice** [comment] 2021-11-15 22:08
Yeah, I updated manually 2.27.0 by https://github.com/ARMmbed/mbedtls/pull/4947/files and it did fix MacOS version of my app compiled with -O2 flag.
Need to check others platforms too. Hope we can see this in official release soon.

**Comment by codeservice** [comment] 2021-11-15 23:19
I tested iOS, fix doesn't help here. Fix works only for MacOS.

**Comment by gilles-peskine-arm** [comment] 2021-11-16 09:05
The bug is in assembly code which is dependent on the CPU, not on the OS. For 32-bit arm, there are several assembly variants. What exact target CPU are you compiling from?

**Comment by codeservice** [comment] 2021-11-16 14:58
For iOS arm64

**Comment by davidhorstmann-arm** [comment] 2021-11-16 16:43
Hmm, that's interesting - this should have been fixed for arm64 (all platforms) by #4978, #4968 and friends. Did you apply this change? (It was buried in many layers of issues, so not very easy to find).

**Comment by codeservice** [comment] 2021-11-16 18:25
Yes, I didnt try second fix before. Now I can see this was missing:
https://github.com/ARMmbed/mbedtls/pull/4968/files
Now MBED works on iOS

**Comment by codeservice** [comment] 2021-11-17 20:44
I manually updated file (#4978, #4968) and fixed issue on MacOS and iOS. But update break android simulator targets now: x86 and x86_64 with error message ehich include domain name and text unable to find host.
Android targets arm64-v8a and armeabi-v7a works correctly.

**Comment by davidhorstmann-arm** [comment] 2021-11-23 11:48
Closing as duplicate of #4116 and friends. See #4943 for more details

**Closed by davidhorstmann-arm** 2021-11-23 11:48 UTC
Labels: bug, Product Backlog, Community
