### ISSUE TITLE
ecp_comb_fixed crash

### ISSUE THREAD

**Issue by vadgri01** [ARMmbed/mbedtls#2240] opened 2018-11-28 14:19 UTC
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
FreeRTOS

**mbed TLS build:**  
Version: 2.9.0
Toolchain: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622
CPU: cortex M33
Board: MPS2+
**Actual behavior**  
When moved to test to new toolchain with cortex M33 the ecp operation crashes, probably because of some kind of wrong compiler optimization. It worked well with older toolchain on Cortex M3.
It happens in this line of code:
c   |= x[i] & ( x[i-1] * adjust );
When adding volatile to the function declaration the crash does not occur. 
static void ecp_comb_fixed( **volatile** unsigned char x[], size_t d,
                            unsigned char w, const mbedtls_mpi *m )

Steps to reproduce
Compile mbedtls with latest  arm-none-eabi-gcc toolchain on cortex M33 and run any test with ecp operations.
---------------------------------------------------------------

**Comment by hanno-arm** [comment] 2018-11-28 14:55
Hi @vadgri01,

thanks for your report. It sound like you suspect a compiler bug as opposed to a bug in the source code. Did you perform any assembly analysis to confirm or refute this? Did you experiment with different compiler optimization flags?

Regards,
Hanno

**Comment by ciarmcom** [comment] 2018-11-28 22:12
ARM Internal Ref: IOTSSL-2645

**Comment by RonEld** [comment] 2018-12-10 09:58
The issue was a missing compilation flag `-march=armv8-m.base`
Closing as not a bug

**Closed by RonEld** 2018-12-10 09:58 UTC
Labels: component: Crypto, mirrored, question, tracking
