### ISSUE TITLE
Same function is called in both cases 

### ISSUE THREAD

**Issue by belhob** [ARMmbed/mbedtls#1896] opened 2018-07-28 06:29 UTC
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug | Question
- Priority: Major 

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: 2.10.0

## Question
Same function is called in both cases 

File: x509_crt.c 
Line: 1012 - 1015

if( buf_format == MBEDTLS_X509_FORMAT_DER )
        return mbedtls_x509_crt_parse_der( chain, buf, buflen );
#else
    return mbedtls_x509_crt_parse_der( chain, buf, buflen );
#endif

**Comment by RonEld** [comment] 2018-07-29 07:38
@belhob Thank you for your interest in Mbed TLS!
This is not a bug. please note that the `#else` statement is a precompilation check, and is an `#else` for the previous:
~~~
#if defined(MBEDTLS_PEM_PARSE_C)
~~~
In short, if we have PEM parsing configured, we first check if the buffer is PEM, and if not, we parse as DER.
If we don't have PEM parsing configured, then we just try to parse the buffer as DER.
I hope this answers your question.

**Comment by RonEld** [comment] 2018-07-29 12:52
Closing, as I believe the question was answered. If you think this issue was not fully addressed, please reopen,

**Closed by RonEld** 2018-07-29 12:52 UTC
Labels: question
