### ISSUE TITLE
Please add get access method for mbedtls_ssl_context state field

### ISSUE THREAD

**Issue by ddemoney** [ARMmbed/mbedtls#5450] opened 2022-01-24 09:10 UTC
Please add get access method for mbedtls_ssl_context state field

To aid in debugging, we report the last state of the TLS handshake before an error occurred.

Also, because our device is not multi-threaded, we cannot block during the handshake (using mbedtls_ssl_handshake_step() instead), and we check the state to determine when the handshake is complete (as is done in mbedtls_ssl_handshake())

**Comment by paul-elliott-arm** [comment] 2022-01-24 15:12
Potential duplicate of https://github.com/ARMmbed/mbedtls/issues/4383

**Closed** 2022-01-24 15:14 UTC
Labels: enhancement, Community
