### ISSUE TITLE
MbedTls 2.26.0 release won't compile with my config

### ISSUE THREAD

**Issue by samhaa01** [ARMmbed/mbedtls#4631] opened 2021-06-09 09:57 UTC
### Summary

MbedTls 2.26.0 release won't compile with a modified config.

### System information

Mbed TLS version (number or commit id): 2.26.0
Operating system and version: Ubuntu 18.04.5 LTS
Configuration (if not default, please attach `config.h`): See `Steps to reproduce` below

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): generated by CMake (3.10.2).

Additional environment information: 

g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Expected behavior

Code compiles by default.

### Actual behavior

Compilation fails.

### Steps to reproduce

To reproduce it:

cd to your git repositories working directory and run:

```
git clone git@github.com:samhaa01/mbedtls -b mbedtls-2.26-compile-problem-config
cd mbedtls
cmake -DUSE_SHARED_MBEDTLS_LIBRARY=On -DENABLE_TESTING=OFF -DENABLE_PROGRAMS=OFF -DCMAKE_BUILD_TYPE=RELEASE .
make
```

### Additional information

Compilation produces errors, for example:

```
/home/samhaa01/gitrepos/for-review/mbedtls/library/x509_crt.c:2080:39: error: ‘serial number     : ’ directive output truncated writing 20 bytes into a region of size between 0 and 1 [-Werror=format-truncation=]
     ret = mbedtls_snprintf( p, n, "%sserial number     : ",
                                      ~^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /home/samhaa01/gitrepos/for-review/mbedtls/include/mbedtls/bignum.h:35,
                 from /home/samhaa01/gitrepos/for-review/mbedtls/include/mbedtls/asn1.h:34,
                 from /home/samhaa01/gitrepos/for-review/mbedtls/include/mbedtls/x509.h:31,
                 from /home/samhaa01/gitrepos/for-review/mbedtls/include/mbedtls/x509_crt.h:31,
                 from /home/samhaa01/gitrepos/for-review/mbedtls/library/x509_crt.c:36:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output 21 or more bytes (assuming 22) into a destination of size 1
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
library/CMakeFiles/mbedx509_static.dir/build.make:182: recipe for target 'library/CMakeFiles/mbedx509_static.dir/x509_crt.c.o' failed
make[2]: *** [library/CMakeFiles/mbedx509_static.dir/x509_crt.c.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'library/CMakeFiles/mbedx509_static.dir/all' failed
make[1]: *** [library/CMakeFiles/mbedx509_static.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
I think the errors happen, because compile warning level has been increased. I have made a work-around. 

See my commit:

https://github.com/samhaa01/mbedtls/tree/mbedtls-2.26-compile-fix

**Comment by gilles-peskine-arm** [comment] 2021-06-09 10:38
This has already been fixed in the development branches. We overhauled printf specifiers and related warning flags in https://github.com/ARMmbed/mbedtls/pull/3579. I've verified locally that on https://github.com/samhaa01/mbedtls/tree/mbedtls-2.26-compile-problem-config, I can reproduce the build failure with GCC 7 (on Ubuntu 18.04 as well), but if I cherry-pick the configuration-changing commit to the [`development_2.x`](https://github.com/ARMmbed/mbedtls/tree/development_2.x) branch, the build goes through.

**Comment by mpg** [comment] 2021-06-15 10:46
Since this is already fixed in `development_2.x`, I'm closing this issue as there's nothing for us to do here, but thanks for your report!

**Closed by mpg** 2021-06-15 10:46 UTC
Labels: Community, bug, fix available
