### ISSUE TITLE
3.x: Make handshake->state or mbedtls_ssl_handshake_is_over() public

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4931] opened 2021-09-09 18:54 UTC
The documentation of `mbedtls_ssl_handshake_step` suggests that applications should inspect `ssl->state` and compare it with `MBEDTLS_SSL_HANDSHAKE_OVER`. In Mbed TLS 3.0, `state` has become a private field. One of the following needs to happen:

* Find and document another way to determine whether the handshtake is over.
* Make `state` public.
* A new accessor function `mbedtls_ssl_get_handshake_state`.
* A new boolean function `mbedtls_ssl_handshake_is_over`.

I'm leaning towards `mbedtls_ssl_handshake_is_over`, which allows the set of handshake states to change (is this needed for 1.3) without risking affecting application code.

Needed to properly migrate Zephyr to Mbed TLS 3. See https://github.com/openthread/openthread/pull/7001

**Comment by neoxic** [comment] 2021-12-06 04:33
Just adding `mbedtls_ssl_handshake_is_over()` is not enough. A new accessor function `mbedtls_ssl_get_handshake_state()` is required for fine-grained handshake control.

**Comment by mpg** [comment] 2021-12-17 09:47
I think this is a duplicate of #4383, which also has more discussion on what exactly is needed, so I'm closing this one.

**Closed by mpg** 2021-12-17 09:47 UTC
Labels: bug, enhancement, component: TLS, Product Backlog, size:S
