### ISSUE TITLE
Remove unnecessary compile-time options from config.h

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4035] opened 2021-01-14 19:01 UTC
This needs review

**Comment by yanesca** [comment] 2021-01-25 12:24
We are removing a number of options as part of #4031 and #4029. Some more will be moved as part of #4038. Options removed or moved as part of these are out of scope for this issue.

First step of this task should be to review `config.h`, make a list of options that we could remove and reach a consensus on which options to remove.

**Comment by mpg** [comment] 2021-02-05 09:38
> First step of this task should be to review config.h, make a list of options that we could remove and reach a consensus on which options to remove.

I think this is #4058 - so perhaps #4058 is about reviewing options to decide which ones to remove, and this ticket would be about actually removing them? (It's not clear to me is such a distinction was intended or if #4058 is mostly an accidental duplicate.)

**Comment by yanesca** [comment] 2021-02-05 09:51
I think #4058 is an accidental duplicate, I suggest we close this ticket down and keep #4058 as it is better specified.

**Comment by mpg** [comment] 2021-02-24 11:29
Closing as a duplicated of #4058, since Janos suggesting doing so more than two weeks ago, I agree, and no-one objected in the meantime.

**Closed by mpg** 2021-02-24 11:29 UTC
Labels: Product Backlog, enhancement, mbedtls-3
