### ISSUE TITLE
Return code of psa_get_key_attributes()

### ISSUE THREAD

**Issue by davidhuziji** [ARMmbed/mbedtls#4607] opened 2021-06-02 14:40 UTC
Hi,

It looks like `psa_get_key_attributes()` implementation in mbed TLS will return `PSA_ERROR_DOES_NOT_EXIST` in some error cases.
However, PSA Crypto API v1.0.0 doesn't list `PSA_ERROR_DOES_NOT_EXIST` as an error code returned by `psa_get_key_attributes()`.

I'm working on some test cases which check the return code from `psa_get_key_attributes()`. For example, if I pass an invalid key or a key which has been destroyed, into `psa_get_key_attributes()`, which error code shall I expect? Are  `PSA_ERROR_INVALID_HANLDE` and `PSA_ERROR_DOES_NOT_EXIST` both valid return codes?

Could you please clarify the error codes? Thanks!

**Comment by gilles-peskine-arm** [comment] 2021-06-02 15:40
`psa_get_key_attributes` should return `PSA_ERROR_INVALID_HANDLE` for a non-existent key, regardless of whether the handle value would be a valid one for a key.

We fixed a bug like this in https://github.com/ARMmbed/mbedtls/pull/4198. It hasn't been part of a release yet. Did you observe this bug in on a recent checkout of the `development` or `development_2.x` branch? If so can you please let us know how to reproduce the bug?

**Comment by davidhuziji** [comment] 2021-06-03 01:36
Hi Gilles, it is found in v2.26.0 so it should be a known issue. Thanks for sharing the patch link.

**Comment by gilles-peskine-arm** [comment] 2021-06-03 08:02
This issue appears to be a duplicate of https://github.com/ARMmbed/mbedtls/issues/4162 (which is fixed in development but the fix hasn't been released yet) so I'm closing it.

**Closed by gilles-peskine-arm** 2021-06-03 08:02 UTC
