### ISSUE TITLE
Error mbedtls_pk_verify MBEDTLS_ERR_RSA_VERIFY_FAILED

### ISSUE THREAD

**Issue by chtavares592** [ARMmbed/mbedtls#1696] opened 2018-06-06 18:22 UTC
I'm developing on Zephyr Project a library http_client and that library receive a server_signature (BASE64), that signature is made with a hash(sha256) of the string and the private key. At my library, I catch my public key and call "mbedtls_pk_parse_public_key" and runs everything right. In order to verify I call "mbedtls_pk_can_do( &pk, MBEDTLS_PK_RSA )" and "mbedtls_rsa_check_pubkey" and that functions return 0.
After I decode the server_signature using "mbedtls_base64_decode" and return 0.
But, when I call the verification function "mbedtls_pk_verify" returns MBEDTLS_ERR_RSA_VERIFY_FAILED, don't understand the reason.

I already tested the same data using OpenSSL and the verification returns true.

Bellow had where I do the verification, hash of data and public_key.

```
hash = "5b0908ea3740745c383cd21bb1436d2e715f7e85ae607ff9f278b0239bd7cd2f"

static const char server_signature[] = {
     "PsvfcGyV9boBqnXeJhkXGfoZVKE4+QyxAqsmB0OzmW1csA5neZCNLBeG6NncVbrS"
     "3Yq3mfqbe2RmbIi3oMKEfzeVarfLRQPcc/c3aaA9zqw6713dzYZj5Jdwo7h9a7LO"
     "/6NBQKQBMo+hDFQFndPdl9Y2eGpGphecbMjfu288UcwtQn/FBCs8ZaYIY7O8VmNS"
     "04J27Jp0dhbVGWqDWiWd2aGSgQ/6hfs39b0aDpE3OkgU/K4Ol4t0YLtmBXZAFIs2"
     "lElkqS1sfgHp3kllp5inpTZ1KWAjqP1jQgCkD7MxeZau7roryNdzRUDPAjlC0lZ3"
     "WuY7nBXSMtUNQPV05FWxKDxECQIdIETDDa48qBPTpUCkv+du5Otwi3g5ajLTWz9S"
     "zyw+zXS28znPlXHAnKlWYejy3zsBpBNsza8vhx0NwfUbdW/3R0oW5WtlrqVOLkJE"
     "XYdPUFyryrcyirNsVwa5yTBCZCoRTC0Us0/kRSqZeT/Z6lBkA/A3vMmaDhnG7VZ7"
     "WJtXium/OtBIVgPwQFmHNQ9Bu/5HLqV/qqSApoLihNHr1iAhpRXoY5XHMujzDzmZ"
     "kYJeqewz7hVEoQHITldW8Uny6SwQaWDlgFTcgyKSE60ULaX9TFzy0wz3xvGxqjZD"
     "ZXQ7WkCcbjcusXBAxCp/bI/LFtKdxUcEavaGYwg1ZRg="
};

static const char public_key[] = {
	"-----BEGIN PUBLIC KEY-----\r\n"
	"MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyiPEMdY1tBIH9YXo4IFw\r\n" 
	"dLLy9FPA1+bkfSFlHFRXZ+DIkfe/V36elvkfJmm3nM0HYqbDY+vqSE284VW3VeZA\r\n" 
	"n0VNOlgvOQQ5foDlHSA7qv1OTlMXmVmZjY6GArjl5haDM1jkqLPUP2vbS7UJ2y/z\r\n" 
	"SdJc83l2hpExapFMCUgTDDSBc0vKZRIjspjkJ0+dL7/K8UKDl/8QvF+q/j7REbne\r\n"
	"EYqyo/lwaf9EKzZvtsF6gphxT/eNKWbhlYEZrrHzydITceuxGqTlBV3Nn+tkCi+P\r\n" 
	"ADgG/VPa1BG0b5xEyo6e12KgKJKMUmrvDh9UwXYvaWVKImzE0DCAVqbHNQInAtzs\r\n" 
	"WkHW04w+Oeornbok57cZOMpG4fVHtMtLdFU/zRl2HxKqs+QLv8jh8JfY0MuPgqpW\r\n" 
	"AtDwjyPMls4UrrrO3lWOPl5752GjcMmK27CSBI7g9XKsD/soM4/gmp2uuLRR5eMy\r\n" 
	"wd3jeLjBu9f21A9YB1PoCyj21Kyx8PyXmaflNdWb5C1EOtsIR9J42Iua1K7Z3S0y\r\n"
	"RkpUxikR4l0LZ0gNa19+v1qqYye0qw+WzIBZk9VJPLp0i4lYaSlo/5kVUOXPeo5V\r\n" 
	"Gf6+p6qVpuvd3pC6X/P1JnlObocQ8iaxEzmazzEUDN7gDAszpVMwNedpKKssw8uN\r\n" 
	"aFHCXEDJgsstBC86OkLK64MCAwEAAQ==\r\n" 
	"-----END PUBLIC KEY-----\r\n"
};

static int updatehub_check_signature(struct updatehub_context *ctx, char *package_uid)
{
	int ret, i, j, k, aux;
        char *dst;
	size_t olen = 0;
	mbedtls_pk_context pk;

 	mbedtls_pk_init(&pk );
	SYS_LOG_DBG("signature %d", strlen(server_signature));

	ret = mbedtls_pk_parse_public_key(&pk, public_key, strlen(public_key) + 1);
	if(ret != 0)
	{
		SYS_LOG_DBG("error parsing the public_key, %d", ret);
		return ret;
	}	

	
   if( !mbedtls_pk_can_do( &pk, MBEDTLS_PK_RSA ) )
    {
        ret = 1;
        SYS_LOG_DBG( "failed! Key is not an RSA key\n" );
        return ret;
    }
    ret = mbedtls_rsa_check_pubkey(mbedtls_pk_rsa(pk));
   if(ret != 0)
	{
		SYS_LOG_DBG("Check pubkey failed");
		ctx->error_msg = "Check pubkey failed";
		return ret;
	}

	dst = k_malloc(512);
	memset(dst, 0, sizeof(dst));
	
       ret = mbedtls_base64_decode(dst, 512, &olen, signature, strlen(signature));
	if(ret != 0)
	{
		SYS_LOG_DBG("decode base64 failed");
		return ret;
	}

	ret = mbedtls_pk_verify(&pk, MBEDTLS_MD_SHA256, hash, 0, dst, 512);
	 if(ret != 0)
	{
		SYS_LOG_DBG("verify failed %d", ret);
	}
	
	k_free(dst);
	
	return 0;
	
}

```

**Comment by chtavares592** [comment] 2018-06-08 13:52
Here https://github.com/chtavares592/verify_signature I developed a simple example on zephyr that my http_client needs to verify the signature.. and the same error occurs. I put the zephyr's app, the server and the keys. I don't know the reason for this problem if somebody can help I will be grateful.

**Comment by RonEld** [comment] 2018-06-10 11:03
@chtavares592 Thank you for your interest in Mbed TLS!

In brief look, I don't see something wrong in the *flow* of your calls.
But I do have a couple of general comments, which may cause some of your issues:
1. In your example, you have set `hash`as a string literal, and sent the sting literal( its length is 64 bytes) to `mbedtls_pk_verify()`, while the verification function receives the hash as a hex buffer( with buffer size of 32 bytes). This could be one of the causes for your failure.
2. I have seen in this example, and in your example link, that you refer length of pointers as `sizeof` which does not return the actual size of the buffer! When you call `sizeof(pointer)`, it will return a size according to your platform architecture ( I assume 4 or 8 in your environment, but there are some architectures with smaller pointer lengths). So when you write your buffers, you may not write the full data that you think you  are writing.

**Comment by chtavares592** [comment] 2018-06-11 14:31
@RonEld thanks for you answer me. I followed your tips and corrected that problems and I resolved to simplify the code removing the server side and letting just application working. But the problem doesn't resolve yet If you could see again o code modified I'll be grateful to help me. Thanks again. 
https://github.com/chtavares592/verify_signature/blob/master/verify_signature/src/main.c

**Comment by RonEld** [comment] 2018-06-11 15:02
@chtavares592 I can't seem to find something wrong in your flow, (except a memory leak in your `dst` variable), assuming your hash function is correct.
You should verify that you have are using the public key which private key pair was used to generate the signature, of this specific hash.
You should erify that the input of the hash is as you think ( is the length 17 on both signing and verification?) You should check that the signature is in the correct byte order.

**Comment by chtavares592** [comment] 2018-06-11 16:55
@RonEld I corrected the memory leak at dst variable. I already verify the keys and they are right. And the hash is ok too. I put a verification if my system is little or big endian and it is little endian equal the server.
https://github.com/chtavares592/verify_signature/blob/master/verify_signature/src/main.c

**Comment by RonEld** [comment] 2018-06-12 14:50
@chtavares592 I can't spot anything wrong in your flow.
I took your public key, signature and data and integrated them to the `pk_verify`  sample application and got the same result.
The only thing I could think about at the moment is that at east one of your parameters you are using is incorrect.
1. Is the signature encoded in base64 correct? Is it the correct signature?
2. Is this the actual public key?
3. Is the data content and length correct?

**Comment by chtavares592** [comment] 2018-06-12 19:55
@RonEld sorry to delay to answer.I'm trying to resolve this problem. I generated a new of key pairs and the signature on OpenSSL on the terminal and put in my app. The great news is the diff is less the others tests, now 19 diffs. But I continuous check my parameters and don't know the problem...  Thanks for helping me.

**Comment by chtavares592** [comment] 2018-06-13 20:06
@RonEld , Do you know if there is an alternative form to verify the RSA signature?

**Comment by RonEld** [comment] 2018-06-14 07:56
@chtavares592 you could try directly the`rsa` module instead of the pk wrapper, but I doubt it would help.
The fact that you now have 199 diffs instead of 22 diffs does really matter. You shouldn't get any difference.

**Comment by RonEld** [comment] 2018-06-14 11:21
@chtavares592 WE can't see anything wrong in the flow.
I would suggest you look how you generate the signature as well

**Comment by chtavares592** [comment] 2018-06-14 12:13
@RonEld I'm signed with command line  `echo -n test-verification | sha256sum | openssl dgst -sha256 -sign  private_key.pem -out /tmp/sign.sha256 -` on terminal and after I use the conversion of base64 `openssl base64 -in /tmp/sign.sha256 -out base64.txt` for to get the signature.
The sha256sum is the same of my application.

**Comment by chtavares592** [comment] 2018-06-14 12:51
@RonEld Now I changed my app and I sign and verify at the same app, and I get the signature is completely different than OpenSSL -sign or the node js signature... But returns zero the pk_verify function. If you could see my new implementation. Thanks. https://github.com/chtavares592/verify_signature/blob/master/verify_signature/src/main.c

**Comment by chtavares592** [comment] 2018-06-14 14:15
@RonEld Indeed the problem is with the signature. I was able to get the signature through the pk_sign function and set it to "static unsigned char signature_ph_sign". The OpenSSL signature is the same as node js and completely different from pk_sign. Now I wanted to understand why this difference occurs, which makes the signatures so different. thank you. You can see here https://github.com/chtavares592/verify_signature/blob/master/verify_signature/src/main.c

**Comment by chtavares592** [comment] 2018-06-14 20:15
@RonEld I finally can verify the signature, I found my mistake... I was signing the sha256sum of data's sha256sum. Thanks for helping and sorry for my dumb mistake.

**Comment by RonEld** [comment] 2018-06-17 05:11
@chtavares592 
I am glad you resolved your issues. Mistakes happen. to answer your question:
> Now I wanted to understand why this difference occurs, which makes the signatures so different. 

When signing, there is a random element(notice you send a callback to the `f_rng`), which makes the signature different in every call. This is why it's strange you got same value in openssl as node js.

I am now closing this issue, as the issue is resolved.

**Closed by RonEld** 2018-06-17 05:11 UTC
Labels: question
