### ISSUE TITLE
mbedtls_ssl_handshake() and MBEDTLS_SSL_HANDSHAKE_OVER

### ISSUE THREAD

**Issue by github-monoculture** [ARMmbed/mbedtls#518] opened 2016-06-22 13:28 UTC
Due to circumstances, there were time when my code would call mbedtls_ssl_handshake() when ssl->state was MBEDTLS_SSL_HANDSHAKE_OVER.
It returns 0, which is not really what you'd expect.
(Not hard to work around by checking the state field first, of course.)
Reading the code, it looks like if a client were to call mbedtls_ssl_handshake_step() repeatedly to get through handshake instead, mbedtls_ssl_handshake_client_step() would return MBEDTLS_ERR_SSL_BAD_INPUT_DATA for MBEDTLS_SSL_HANDSHAKE_OVER.

**Comment by ciarmcom** [comment] 2016-06-22 15:51
ARM Internal Ref: IOTSSL-834

**Comment by mpg** [comment] 2018-10-25 11:14
@github-monoculture thanks for your report and sorry for the late reply!

I think the code is behaving as expected and as described by the documentation: for `mbedtls_ssl_handshake_step()` it [states](https://github.com/ARMmbed/mbedtls/blob/c774e329390293b4f3cafadea86b3feb5579e36f/include/mbedtls/ssl.h#L2952) "Do not call this function if state is MBEDTLS_SSL_HANDSHAKE_OVER." while the is no similar statement for `mbedtls_ssl_handshake()`. This is consistent with the fact that one returns an error in that case but not the other.

This difference in behaviour might be surprising at first, but I think it's correct if we consider what each function is supposed to be doing: `handshake_step()` performs exactly one step, which can't be done if the is no longer any step to perform, while `handshake()` does whatever is necessary to complete the handshake, so "nothing left to do" is an acceptable condition: the function will do nothing and the handshake will be completed successfully, so it return `0` for success.

Therefore, we're closing this as "not a bug", but feel free to comment or re-open if you disagree.

**Closed** 2018-10-25 11:47 UTC
Labels: bug, mirrored, tracking
