### ISSUE TITLE
dtls_server fails on macOS

### ISSUE THREAD

**Issue by highwall** [ARMmbed/mbedtls#859] opened 2017-03-24 11:04 UTC
Environment
-------------
* System macOS 10.12.3

Steps
-------
```
make
# on one terminal
./programs/ssl/dtls_server

  . Loading the server cert. and key... ok
  . Bind on udp/*/4433 ... ok
  . Seeding the random number generator... ok
  . Setting up the DTLS data... ok
  . Waiting for a remote connection ... ok
  . Performing the DTLS handshake... hello verification requested
  . Waiting for a remote connection ... failed
  ! mbedtls_net_accept returned -74

Last error was: -74 - NET - Could not accept the incoming connection
# on second terminal
./programs/ssl/dtls_client

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to udp/localhost/4433... ok
  . Setting up the DTLS structure... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x4c

Last error was: -76 - NET - Reading information from the socket failed
```
Debug
-------
After debugging I believe this is a bug of macOS's `connect()`.  It fails to connect second time giving error that `Invalid Argument`. I posted it here if someone is able to have Apple get this issue fixed.

**Comment by sbutcher-arm** [comment] 2017-03-24 18:30
I tested this on my own Mac, and found it worked fine. Are you sure this isn't a configuration issue of some sort on your own machine?

**Comment by sbutcher-arm** [comment] 2017-04-10 10:47
Closing as I don't think there's an issue here. Please reply or respond if you think we've misunderstood and see an error!

**Closed by sbutcher-arm** 2017-04-10 10:47 UTC
Labels: question

**Comment by catenacyber** [comment] 2018-05-07 15:43
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
MacOS

**mbed TLS build:**  
Version: 2.7.0 or git commit id 32605dc83042d737e715a685e53176388d73540e
OS version: Darwin Kernel Version 17.5.0
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  default cmake and make

**Peer device TLS stack and version**  
MbedTLS
Version:  2.7.0

**Expected behavior**   
dtls_client should manage to connect to dtls_server 

**Actual behavior**  
dtls_server does not accept connection from dtls_client
Output is 
```

  . Loading the server cert. and key... ok
  . Bind on udp/*/4433 ... ok
  . Seeding the random number generator... ok
  . Setting up the DTLS data... ok
  . Waiting for a remote connection ... ok
  . Performing the DTLS handshake... hello verification requested
  . Waiting for a remote connection ... failed
  ! mbedtls_net_accept returned -74
```

In fact `connect( bind_ctx->fd, (struct sockaddr *) &client_addr, n )`returns an error with `errno=EINVAL`

If I change dtls_server.c so that mbedtls_net_bind specifies "127.0.0.1" instead of all addresses, we get the expected behavior.
There seems to be an explanation here https://patchwork.ozlabs.org/patch/744588/
If I understand, `connect`does not know which address to use

**Steps to reproduce**  

Compile dtls_client and dtls_server and run them both

**Comment by RonEld** [comment] 2018-05-07 15:48
Hi @catenacyber thank you for your information.
I believe that what you are describing is already described in #977

**Comment by redtangent** [comment] 2018-05-12 20:06
I created a PR for this issue #1627, which in my view addresses the problem.

This has only been tested on OSX.

**Comment by mpg** [comment] 2018-05-21 08:10
@redtangent I'm afraid I can't remember why the client is forcing IPv4. At first glance, I support a change like the one you're suggesting in #1627 (provided it's also tested on Linux machines and doesn't break things there).
