### ISSUE TITLE
mbedtls accepts a certificate whose serial number is zero

### ISSUE THREAD

**Issue by chenchuAtXidian** [ARMmbed/mbedtls#801] opened 2017-02-13 14:28 UTC
Summary: As for a certificate, its serial number should be a non-zero positive integer according to RFCs 5280 and 6818.
   
   Versions of mbedTLS: 2.3.0
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  mbedtls_cert_app mode='file' filename=14.pem ca_file=ca.pem
   
   Actual results: OK
   Expected results: mbedTLS should reject such a certificate.
   
   The attachement contains ca.pem and 14.pem.
   
   Please rename the file "test cases.txt" to "test cases.zip" and extract it.

[test cases.txt](https://github.com/ARMmbed/mbedtls/files/771327/test.cases.txt)

**Comment by ciarmcom** [comment] 2017-02-13 20:50
ARM Internal Ref: IOTSSL-1217

**Comment by NWilson** [comment] 2017-02-15 22:08
I don't think this is a bug. Which sentence are looking at in the RFCs? The text of RFC 5280 says:

> Note: Non-conforming CAs may issue certificates with serial numbers that are negative or zero.  Certificate users SHOULD be prepared to gracefully handle such certificates.

Although "gracefully" is not normative standards-language, a sensible interpretation would be "handle the certificate" - which is the opposite of your expectation that it ought to be rejected.

**Comment by sbutcher-arm** [comment] 2017-02-15 22:26
Hi @NWilson.

As you probably know, we use github for interacting with the community and have a backend for managing the work of the team.

Some of these X.509 issues are marked as 'bugs', not because we see it as a defect right now, but because they merited further study before we decide what to do, and that's why they were labelled as 'bug' and 'tracking'.

Right now I have an open mind, and I would not assume this will lead to a code change.

Your opinion is always welcome, and sorry if this was misleading. Maybe we should have an 'investigate' or 'analysis required' label.

**Comment by chenchuAtXidian** [comment] 2017-08-03 12:53
Hi @sbutcher-arm  

How to recognize a bug that is seen as a defect by your team?

**Comment by mpg** [comment] 2018-03-19 12:24
Thanks for your report! After checking RFC 5280, we also think the requirement to enforce that the serial number is a positive integer only applies to issuing CAs, not validating parties (which are rather encouraged _not_ to enforce it as @NWilson says).

Therefore, I'm closing this a "not a bug". Again, feel free to re-open if you disagree, but you'll want to quote precise excerpts from the standard supporting your point of view.

Regarding the "bug" label, it's only as opposed to "feature requests": we currently don't have labels to distinguish between potential bugs and confirmed bugs, so the "bug" label applies to both. Usually a bug is not considered confirmed until we posted a comment acknowledging it.

**Closed by mpg** 2018-03-19 12:24 UTC
Labels: bug, mirrored, tracking
